import { describe, expect, it } from "vitest";
import { autoCheckoutOpenSession, calculateAttendanceSummary, checkInAttendance, deriveDutyStatus, manualCheckout, normalizeLeaveType, type AttendanceSession } from "./attendanceEngine";
import { LIBYA_MARKET_DEFAULT, type BusinessCalendarException } from "./marketSettings";

const open = (): AttendanceSession => checkInAttendance({ id: "S1", userId: "U1", marketId: LIBYA_MARKET_DEFAULT.marketId, countryId: LIBYA_MARKET_DEFAULT.countryId, date: "2026-08-16", timezone: LIBYA_MARKET_DEFAULT.timezone, scheduledStart: "2026-08-16T05:30:00Z", scheduledEnd: "2026-08-16T13:30:00Z", actualCheckIn: "2026-08-16T05:35:00Z", createdBy: "U1", createdAt: "2026-08-16T05:35:00Z", updatedBy: "U1", updatedAt: "2026-08-16T05:35:00Z" }, 15);
const holiday: BusinessCalendarException = { id: "H", marketId: LIBYA_MARKET_DEFAULT.marketId, countryId: LIBYA_MARKET_DEFAULT.countryId, date: "2026-08-17", nameEn: "Holiday", nameAr: "عطلة", type: "PUBLIC", active: true, createdBy: "A", createdAt: "x", updatedBy: "A", updatedAt: "x" };

describe("WP77C attendance, workday and Team Activity engine", () => {
  it("manual checkout closes normally and later auto-checkout is idempotent", () => { const closed = manualCheckout(open(), "2026-08-16T13:05:00Z"); expect(closed.checkoutMode).toBe("MANUAL"); expect(autoCheckoutOpenSession(closed, "2026-08-16T16:00:00Z", 480)).toEqual(closed); });
  it("forgotten checkout closes AUTO but credits only through scheduled end", () => { const closed = autoCheckoutOpenSession(open(), "2026-08-16T16:00:00Z", 480); expect(closed).toMatchObject({ checkoutMode: "AUTO", actualCheckOut: "2026-08-16T13:30:00.000Z", effectiveDurationMinutes: 475 }); });
  it("does nothing before the fallback becomes eligible", () => expect(autoCheckoutOpenSession(open(), "2026-08-16T12:00:00Z", 480).actualCheckOut).toBeUndefined());
  it("normalizes required leave types and legacy Emergency", () => { expect(normalizeLeaveType("work from home")).toBe("WORK_FROM_HOME"); expect(normalizeLeaveType("Emergency")).toBe("PERSONAL"); });
  it("represents holiday, leave, duty and checkout statuses", () => { expect(deriveDutyStatus("2026-08-17", LIBYA_MARKET_DEFAULT, [holiday])).toBe("HOLIDAY"); expect(deriveDutyStatus("2026-08-16", LIBYA_MARKET_DEFAULT, [], undefined, { id: "L", userId: "U1", marketId: LIBYA_MARKET_DEFAULT.marketId, startDate: "2026-08-16", endDate: "2026-08-16", type: "ANNUAL", status: "APPROVED" })).toBe("LEAVE"); expect(deriveDutyStatus("2026-08-16", LIBYA_MARKET_DEFAULT, [], open())).toBe("ON_DUTY"); });
  it("uses scheduled minus approved leave as denominator", () => { const summary = calculateAttendanceSummary({ userId: "U1", fromDate: "2026-08-16", toDate: "2026-08-18", market: LIBYA_MARKET_DEFAULT, exceptions: [holiday], sessions: [manualCheckout(open(), "2026-08-16T13:05:00Z")], leaves: [{ id: "L", userId: "U1", marketId: LIBYA_MARKET_DEFAULT.marketId, startDate: "2026-08-18", endDate: "2026-08-18", type: "SICK", status: "APPROVED" }] }); expect(summary).toMatchObject({ scheduledWorkingDays: 2, approvedLeaveDays: 1, expectedAttendanceDays: 1, workedDays: 1, absences: 0, holidays: 1, manualCheckouts: 1 }); });
});
