import { isActorMarketContext, type ActorMarketContext } from "./operationalScopeClient";
import type { User as FirebaseUser } from "firebase/auth";
export interface OrderWorkflowQueueControls { fromDate?: string; toDate?: string; statuses?: Array<"FINANCE_APPROVED" | "PENDING_OPERATIONS_REVIEW">; pageSize?: number; cursor?: string }
export interface OrderWorkflowQueueSummary { marketId?: string; countryId?: string; currencyCode?: string; marketContext?: ActorMarketContext; kind: "ORDER_WORKFLOW_QUEUE_SUMMARY"; orderId: string; displayNumber: string; pharmacyId: string; pharmacyName: string; representativeName: string; orderDate: string; currentStatus: "FINANCE_APPROVED" | "PENDING_OPERATIONS_REVIEW"; stage: string; itemCount: number; total: number; version: string }
export interface OrderWorkflowQueueResponse { authorized: boolean; code?: string; orders: OrderWorkflowQueueSummary[]; nextCursor?: string }
export type OrderWorkflowQueueState = { status: "UNINITIALIZED" | "LOADING" | "READY" | "DENIED" | "ERROR"; actorUid: string | null; orders: OrderWorkflowQueueSummary[]; code?: string };
export const EMPTY_ORDER_WORKFLOW_QUEUE_STATE: OrderWorkflowQueueState = { status: "UNINITIALIZED", actorUid: null, orders: [] };
const isSummary = (value: any): value is OrderWorkflowQueueSummary => (value?.marketContext === undefined || isActorMarketContext(value.marketContext)) && [value?.marketId, value?.countryId, value?.currencyCode].every(field => field === undefined || typeof field === "string") && value?.kind === "ORDER_WORKFLOW_QUEUE_SUMMARY" && [value.orderId, value.displayNumber, value.pharmacyId, value.pharmacyName, value.representativeName, value.orderDate, value.stage, value.version].every((field) => typeof field === "string") && ["FINANCE_APPROVED", "PENDING_OPERATIONS_REVIEW"].includes(value.currentStatus) && [value.itemCount, value.total].every((field) => typeof field === "number" && Number.isFinite(field));
export const isOrderWorkflowQueueResponse = (value: any): value is OrderWorkflowQueueResponse => value && typeof value.authorized === "boolean" && Array.isArray(value.orders) && value.orders.every(isSummary) && (value.code === undefined || typeof value.code === "string") && (value.nextCursor === undefined || typeof value.nextCursor === "string");
export async function fetchOrderWorkflowQueue(user: Pick<FirebaseUser, "getIdToken">, controls: OrderWorkflowQueueControls = {}, fetchImplementation: typeof fetch = fetch): Promise<OrderWorkflowQueueResponse> { const token = await user.getIdToken(); const response = await fetchImplementation("/api/orders/workflow/scoped-query", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(controls) }); const payload = await response.json(); if (!isOrderWorkflowQueueResponse(payload)) throw new Error("Malformed order-workflow-queue response"); return payload; }
export function createOrderWorkflowQueueReadController(loader = fetchOrderWorkflowQueue) { let state = EMPTY_ORDER_WORKFLOW_QUEUE_STATE; let generation = 0; return { getState: () => state, async load(actorUid: string, user: Pick<FirebaseUser, "getIdToken">, controls: OrderWorkflowQueueControls = {}) { const current = ++generation; state = { status: "LOADING", actorUid, orders: [] }; try { const result = await loader(user, controls); if (current !== generation) return; state = result.authorized ? { status: "READY", actorUid, orders: result.orders } : { status: "DENIED", actorUid, orders: [], code: result.code }; } catch { if (current === generation) state = { status: "ERROR", actorUid, orders: [] }; } }, clear() { generation += 1; state = EMPTY_ORDER_WORKFLOW_QUEUE_STATE; } }; }
export interface OrderOperationsTransitionResponse { success: boolean; code?: string; orderId?: string; currentStatus?: string }
export async function executeOrderOperationsTransition(user: Pick<FirebaseUser, "getIdToken">, request: { orderId: string; action: string; comments?: string; expectedStatus: string; expectedVersion: string }, fetchImplementation: typeof fetch = fetch): Promise<OrderOperationsTransitionResponse> { const token = await user.getIdToken(); const response = await fetchImplementation("/api/orders/workflow/transition", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(request) }); const payload = await response.json(); if (!payload || typeof payload.success !== "boolean" || (payload.code !== undefined && typeof payload.code !== "string")) throw new Error("Malformed order-operations-transition response"); return payload; }
