import fs from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { PharmacyVisit } from "../types";
import { createPharmacyVisitReadController, fetchScopedPharmacyVisits } from "./pharmacyVisitReadClient";

const visit = (id: string): PharmacyVisit => ({ id, pharmacyId: "PH1", pharmacyName: "Pharmacy", repId: "REP1", repName: "Rep", visitDate: "2026-08-01", gpsVerified: true, visitPurpose: "Order Intake", items: [], totalAmount: 0, discountApplied: 0, netAmount: 0, stockAudit: [], intelNotes: "", createdAt: "2026-08-01T00:00:00Z" });
const tokenProvider = { getIdToken: vi.fn(async () => "SECRET_TOKEN") };
afterEach(() => vi.restoreAllMocks());

describe("WP5.2F.5B pharmacy visit-history client and migration boundary", () => {
  it("30. client sends Firebase bearer token", async () => { const fetchMock = vi.fn(async (_url, init) => { expect((init?.headers as Record<string, string>).Authorization).toBe("Bearer SECRET_TOKEN"); return new Response(JSON.stringify({ authorized: true, visits: [] }), { status: 200 }); }); await fetchScopedPharmacyVisits(tokenProvider, {}, fetchMock as typeof fetch); expect(fetchMock).toHaveBeenCalledOnce(); });
  it("31. token is neither persisted nor logged", () => { const source = fs.readFileSync(new URL("./pharmacyVisitReadClient.ts", import.meta.url), "utf8"); expect(source).not.toMatch(/localStorage|sessionStorage|console\.(log|info|warn|error)\([^)]*token/i); });
  it("32. logout clears history", async () => { const controller = createPharmacyVisitReadController(async () => ({ authorized: true, visits: [visit("V1")] })); await controller.load("UID1", tokenProvider); controller.clear(); expect(controller.getState()).toEqual({ status: "UNINITIALIZED", actorUid: null, visits: [] }); });
  it("33. UID transition clears old history", async () => { let resolveNew!: (value: any) => void; const pending = new Promise(resolve => { resolveNew = resolve; }); const loader = vi.fn().mockResolvedValueOnce({ authorized: true, visits: [visit("OLD")] }).mockReturnValueOnce(pending); const controller = createPharmacyVisitReadController(loader); await controller.load("UID1", tokenProvider); const loading = controller.load("UID2", tokenProvider); expect(controller.getState()).toEqual({ status: "LOADING", actorUid: "UID2", visits: [] }); resolveNew({ authorized: true, visits: [visit("NEW")] }); await loading; expect(controller.getState().visits.map(v => v.id)).toEqual(["NEW"]); });
  it("34. operational-scope denial or error clears App history", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain('operationalScopeSession.status !== "READY"'); expect(app).toContain("setStableState(setPharmacyVisits, [])"); });
  it("35. no legacy pharmacyVisits listener fallback remains", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain("createPharmacyVisitReadController"); expect(app).not.toContain('listenCollection<PharmacyVisitType>("pharmacyVisits"'); expect(app).not.toMatch(/collection\(db, "pharmacyVisits"\)[\s\S]{0,100}where\("repId"/); });
  it("36. pharmacy directory READ does not grant history", () => { const service = fs.readFileSync(new URL("../../server/pharmacyVisitReadService.ts", import.meta.url), "utf8"); expect(service).toContain("APPROVED_HISTORY_ROLES"); expect(service).toContain("PHARMACY_VISIT_HISTORY_ROLE_DENIED"); });
  it("37. history READ does not grant execution order payment or sample authority", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); const router = fs.readFileSync(new URL("../components/SidebarPageRouter.tsx", import.meta.url), "utf8"); const execution = fs.readFileSync(new URL("../components/PharmacyVisit.tsx", import.meta.url), "utf8"); expect(app).toContain("handleCompletePharmacyVisit={handleCompletePharmacyVisit}"); expect(router).toContain("onCompletePharmacyVisit={handleCompletePharmacyVisit}"); expect(execution).toContain("onCompletePharmacyVisit(completedVisit)"); expect(execution).not.toContain("pharmacyVisitReadClient"); });
  it("38. physician visit-history behavior remains unchanged", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain("createPhysicianVisitReadController"); expect(app).toContain("setStableState(setPhysicianVisits, state.status"); });
  it("39. PharmacyList and SalesOrders use canonical backend order reads", () => { const list = fs.readFileSync(new URL("../components/PharmacyList.tsx", import.meta.url), "utf8"); const orderClient = fs.readFileSync(new URL("./pharmacyOrderReadClient.ts", import.meta.url), "utf8"); const salesOrders = fs.readFileSync(new URL("../components/sales/SalesOrders.tsx", import.meta.url), "utf8"); const visitClient = fs.readFileSync(new URL("./pharmacyVisitReadClient.ts", import.meta.url), "utf8"); expect(list).not.toMatch(/onSnapshot\(collection\(db, ["']orders["']\)/); expect(list).toContain("createPharmacyOrderReadController"); expect(orderClient).toContain('"/api/pharmacy-orders/scoped-query"'); expect(salesOrders).toContain("fetchScopedCommercialRead"); expect(visitClient).toContain('"/api/pharmacy-visits/scoped-query"'); });
  it("40. no production data schema or rules workaround was introduced", () => { const server = fs.readFileSync(new URL("../../server/pharmacyVisitReadService.ts", import.meta.url), "utf8"); expect(server).toContain("delete redacted[field]"); expect(server).not.toMatch(/\.doc\([^)]*\)\s*\.(set|update|delete|create)\s*\(|\.(add|create)\s*\(|(?:batch|bulkWriter|transaction)\.(set|update|delete|create)\s*\(|writeBatch\s*\(|runTransaction\s*\(|bulkWriter\s*\(|firebase deploy/); });
  it("28. malformed endpoint response fails closed", async () => { const fetchMock = vi.fn(async () => new Response(JSON.stringify({ authorized: true }), { status: 200 })); const controller = createPharmacyVisitReadController(user => fetchScopedPharmacyVisits(user, {}, fetchMock)); await controller.load("UID1", tokenProvider); expect(controller.getState()).toEqual({ status: "ERROR", actorUid: "UID1", visits: [] }); });
});
