import fs from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { PhysicianVisit } from "../types";
import { createPhysicianVisitReadController, fetchScopedPhysicianVisits } from "./physicianVisitReadClient";

const visit = (id: string): PhysicianVisit => ({ id, physicianId: "PHY1", physicianName: "Doctor", repId: "REP1", repName: "Rep", areaId: "A1", visitDate: "2026-08-01", durationSeconds: 60, detailing: [], samples: [], additionalSampleRequests: [], prescriptionIntent: 0, generalNotes: "", gpsVerified: true, createdAt: "2026-08-01T00:00:00Z" });
const tokenProvider = { getIdToken: vi.fn(async () => "SECRET_TOKEN") };
afterEach(() => vi.restoreAllMocks());

describe("WP5.2F.5A physician visit-history client and migration boundary", () => {
  it("25. client sends Firebase bearer token", async () => { const fetchMock = vi.fn(async (_url, init) => { expect((init?.headers as Record<string, string>).Authorization).toBe("Bearer SECRET_TOKEN"); return new Response(JSON.stringify({ authorized: true, visits: [] }), { status: 200 }); }); await fetchScopedPhysicianVisits(tokenProvider, {}, fetchMock as typeof fetch); expect(fetchMock).toHaveBeenCalledOnce(); });
  it("26. token is neither persisted nor logged", () => { const source = fs.readFileSync(new URL("./physicianVisitReadClient.ts", import.meta.url), "utf8"); expect(source).not.toMatch(/localStorage|sessionStorage|console\.(log|info|warn|error)\([^)]*token/i); });
  it("27. malformed endpoint response fails closed", async () => { const fetchMock = vi.fn(async () => new Response(JSON.stringify({ authorized: true }), { status: 200 })); const strict = createPhysicianVisitReadController((user) => fetchScopedPhysicianVisits(user, {}, fetchMock)); await strict.load("UID1", tokenProvider); expect(strict.getState()).toEqual({ status: "ERROR", actorUid: "UID1", visits: [], errorCode: "PHYSICIAN_VISIT_READ_FAILED", errorMessage: "Malformed scoped-physician-visit response" }); });
  it("28. clear on logout removes physician visit history", async () => { const controller = createPhysicianVisitReadController(async () => ({ authorized: true, visits: [visit("V1")] })); await controller.load("UID1", tokenProvider); controller.clear(); expect(controller.getState()).toEqual({ status: "UNINITIALIZED", actorUid: null, visits: [] }); });
  it("29. UID change clears prior history before new load", async () => { let resolveNew!: (value: any) => void; const pendingResponse = new Promise((resolve) => { resolveNew = resolve; }); const loader = vi.fn().mockResolvedValueOnce({ authorized: true, visits: [visit("OLD")] }).mockReturnValueOnce(pendingResponse); const controller = createPhysicianVisitReadController(loader); await controller.load("UID1", tokenProvider); const pending = controller.load("UID2", tokenProvider); expect(controller.getState()).toEqual({ status: "LOADING", actorUid: "UID2", visits: [] }); resolveNew({ authorized: true, visits: [visit("NEW")] }); await pending; expect(controller.getState().visits.map(v => v.id)).toEqual(["NEW"]); });
  it("30. operational-scope denial or error clears App history", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain('operationalScopeSession.status !== "READY"'); expect(app).toContain("setStableState(setPhysicianVisits, [])"); });
  it("31. no legacy physicianVisits listener fallback remains", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain("createPhysicianVisitReadController"); expect(app).not.toContain('listenCollection<PhysicianVisitType>("physicianVisits"'); expect(app).not.toMatch(/collection\(db, "physicianVisits"\)[\s\S]{0,100}where\("repId"/); });
  it("32. physician directory visibility does not grant visit history", () => { const service = fs.readFileSync(new URL("../../server/physicianVisitReadService.ts", import.meta.url), "utf8"); expect(service).toContain("APPROVED_HISTORY_ROLES"); expect(service).toContain("PHYSICIAN_VISIT_HISTORY_ROLE_DENIED"); });
  it("33. visit-history READ does not grant execution actions", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); const router = fs.readFileSync(new URL("../components/SidebarPageRouter.tsx", import.meta.url), "utf8"); const execution = fs.readFileSync(new URL("../components/PhysicianVisit.tsx", import.meta.url), "utf8"); expect(app).toContain("handleCompletePhysicianVisit={handleCompletePhysicianVisit}"); expect(router).toContain("onCompleteVisit={handleCompletePhysicianVisit}"); expect(execution).toContain("isPhysicianEligibleForUser"); expect(execution).toContain("submit: () => onCompleteVisit(completedVisit)"); expect(execution).not.toContain("physicianVisitReadClient"); });
  it("34. existing consumers receive the bounded App physicianVisits array", () => { const router = fs.readFileSync(new URL("../components/SidebarPageRouter.tsx", import.meta.url), "utf8"); expect(router).toContain("physicianVisits={physicianVisits}"); const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain("state.visits"); });
  it("35. pharmacy visit-history migration does not alter physician history", () => { const app = fs.readFileSync(new URL("../App.tsx", import.meta.url), "utf8"); expect(app).toContain("createPhysicianVisitReadController"); expect(app).toContain("setStableState(setPhysicianVisits, state.status"); });
});
