import { describe, expect, it } from "vitest";
import type { Product, SampleAllocation, SampleApproval, SampleBatch, SampleDistribution, SampleInventoryMovement, SampleRequest, SampleSku, User, Physician } from "../types";
import { buildRepresentativeBalanceReport, buildRequestedVsActualPhysicianReport, buildSampleAllocationReport, buildSampleDistributionReport, buildSampleExpiryReport, buildSampleInventoryReport, buildSampleMovementReport, buildSampleRequestLifecycleReport, scopeSampleReportData, type SampleReportDataset } from "./sampleReportingService";

const now = "2026-08-09T10:00:00.000Z";
const sku: SampleSku = { id: "SKU-1", productId: "PROD-1", name: "Test 4 – Trial", descriptor: "Trial", status: "ACTIVE", active: true, createdAt: now, createdBy: "admin", updatedAt: now, updatedBy: "admin" };
const product = { id: "PROD-1", name: "Test 4", stockQuantity: 99999 } as Product;
const users = [{ id: "REP-1", name: "Rep One" }, { id: "REP-2", name: "Rep Two" }, { id: "MGR-1", name: "Manager" }] as User[];
const physicians = [{ id: "PHY-A", name: "Dr A", classification: "A", specialty: "Cardiology" }, { id: "PHY-B", name: "Dr B", classification: "B", specialty: "Internal" }] as Physician[];
const request = (id = "REQ-1", repId = "REP-1", intended: string | undefined = "PHY-A"): SampleRequest => ({ id, requesterId: repId, repId, sampleSkuId: sku.id, productId: product.id, quantityRequested: 20, reason: "Need", requestedForPhysicianId: intended, source: "STANDALONE", urgent: false, status: "AWAITING_ALLOCATION", approvedQuantity: 15, approvalId: `APR-${id}`, createdAt: now, createdBy: repId });
const approval = (req = request()): SampleApproval => ({ id: req.approvalId!, requestId: req.id, repId: req.repId, sampleSkuId: req.sampleSkuId, productId: req.productId, quantityRequested: req.quantityRequested, approverId: "MGR-1", decision: "APPROVED", approvedQuantity: 15, decidedAt: now, createdAt: now, createdBy: "MGR-1" });
const allocation = (id = "AL-1", reqId: string | undefined = "REQ-1", repId = "REP-1"): SampleAllocation => ({ id, sampleSkuId: sku.id, productId: product.id, repId, quantityAllocated: 10, quantityDistributed: 2, quantityRemaining: 8, batchId: "BAT-1", inventoryMovementId: "MOV-AL", requestId: reqId, approvalId: reqId ? `APR-${reqId}` : undefined, allocatedAt: now, allocatedBy: "MGR-1", status: "ACTIVE", reportingMonth: "2026-08", createdAt: now, createdBy: "MGR-1" });
const distribution = (id = "DIST-1", physicianId = "PHY-A", reqId: string | undefined = "REQ-1", repId = "REP-1"): SampleDistribution => ({ id, sampleSkuId: sku.id, productId: product.id, repId, physicianId, quantity: 2, allocationId: "AL-1", batchId: "BAT-1", requestId: reqId, distributedAt: now, createdBy: repId });
const batch: SampleBatch = { id: "BAT-1", sampleSkuId: sku.id, batchNumber: "LOT-1", expiryDate: "2026-12-31", receivedQuantity: 100, availableQuantity: 90, status: "AVAILABLE", createdAt: now, createdBy: "WH-1" };
const movement = (id: string, type: SampleInventoryMovement["type"], sourceId = id): SampleInventoryMovement => ({ id, sampleSkuId: sku.id, batchId: batch.id, type, quantity: type === "RECEIPT" ? 100 : -2, sourceId, sourceType: type === "DISTRIBUTION" ? "SAMPLE_DISTRIBUTION" : type === "ALLOCATION" ? "SAMPLE_ALLOCATION" : type === "ADJUSTMENT" ? "MANUAL_ADJUSTMENT" : "SAMPLE_BATCH", actorId: "MGR-1", createdAt: now });
const dataset = (overrides: Partial<SampleReportDataset> = {}): SampleReportDataset => ({ skus: [sku], products: [product], users, physicians, inventory: [{ sampleSkuId: sku.id, batchId: batch.id, totalReceived: 100, availableQuantity: 90, allocatedQuantity: 10, expiredOrBlockedQuantity: 0 }], batches: [batch], requests: [request()], approvals: [approval()], allocations: [allocation()], distributions: [distribution()], movements: [movement("MOV-R", "RECEIPT"), movement("MOV-A", "ADJUSTMENT"), movement("AL-1", "ALLOCATION", "AL-1"), movement("DIST-1", "DISTRIBUTION", "DIST-1")], ...overrides });

describe("WP-S9 canonical Sample reports", () => {
  it("uses Sample inventory rather than commercial Product stock", () => expect(buildSampleInventoryReport(dataset())[0].availableQuantity).toBe(90));
  it("joins Sample SKU to Product through canonical IDs", () => expect(buildSampleInventoryReport(dataset())[0]).toMatchObject({ sampleSkuId: "SKU-1", productId: "PROD-1", productName: "Test 4" }));
  it("keeps request, approval, and allocation quantities separate", () => expect(buildSampleRequestLifecycleReport(dataset())[0]).toMatchObject({ requestedQuantity: 20, approvedQuantity: 15, allocatedQuantity: 10, remainingApprovedQuantity: 5 }));
  it("does not count approval alone as allocation", () => expect(buildSampleRequestLifecycleReport(dataset({ allocations: [] }))[0].allocatedQuantity).toBe(0));
  it("distinguishes REQUEST allocation", () => expect(buildSampleAllocationReport(dataset())[0].allocationSource).toBe("REQUEST"));
  it("distinguishes DIRECT allocation", () => expect(buildSampleAllocationReport(dataset({ allocations: [{ ...allocation("AL-D"), requestId: undefined, approvalId: undefined }] }))[0].allocationSource).toBe("DIRECT"));
  it("calculates rep balance from canonical allocation remaining", () => expect(buildRepresentativeBalanceReport(dataset())[0].currentRemaining).toBe(8));
  it("uses actual distributions only for physician reporting", () => expect(buildSampleDistributionReport(dataset())[0]).toMatchObject({ distributionId: "DIST-1", physicianId: "PHY-A", quantity: 2 }));
  it("does not infer distributions from requests", () => expect(buildSampleDistributionReport(dataset({ distributions: [] }))).toEqual([]));
  it("classifies a matched intended physician", () => expect(buildRequestedVsActualPhysicianReport(dataset())[0].resultCategory).toBe("MATCHED"));
  it("classifies a different physician without marking invalid", () => expect(buildRequestedVsActualPhysicianReport(dataset({ distributions: [distribution("D2", "PHY-B")] }))[0]).toMatchObject({ resultCategory: "DIFFERENT_PHYSICIAN", complianceViolation: false }));
  it("classifies no intended physician after distribution", () => { const req = { ...request("REQ-N"), requestedForPhysicianId: undefined }; expect(buildRequestedVsActualPhysicianReport(dataset({ requests: [req], approvals: [approval(req)], allocations: [allocation("AL-N", req.id)], distributions: [distribution("D-N", "PHY-B", req.id)] }))[0].resultCategory).toBe("NO_INTENDED_PHYSICIAN"); });
  it("classifies not-yet-distributed requests", () => expect(buildRequestedVsActualPhysicianReport(dataset({ distributions: [] }))[0].resultCategory).toBe("NOT_YET_DISTRIBUTED"));
  it.each(["RECEIPT", "ADJUSTMENT", "ALLOCATION", "DISTRIBUTION"] as const)("includes %s movement", type => expect(buildSampleMovementReport(dataset()).some(item => item.type === type)).toBe(true));
  it("identifies adjustment analytics flag", () => expect(buildSampleMovementReport(dataset()).find(item => item.type === "ADJUSTMENT")?.flags).toContain("ADJUSTMENT"));
  it("uses a display-only near-expiry category", () => expect(buildSampleExpiryReport(dataset(), {}, "2026-11-01T00:00:00.000Z")[0].category).toBe("NEAR_EXPIRY"));
  it("scopes rep reports to authorized IDs", () => { const other = request("REQ-2", "REP-2"); const scoped = scopeSampleReportData(dataset({ requests: [request(), other], approvals: [approval(), approval(other)], allocations: [allocation(), allocation("AL-2", other.id, "REP-2")], distributions: [distribution(), distribution("D-2", "PHY-B", other.id, "REP-2")] }), ["REP-1"]); expect(scoped.requests.map(item => item.repId)).toEqual(["REP-1"]); expect(scoped.allocations.every(item => item.repId === "REP-1")).toBe(true); expect(scoped.distributions.every(item => item.repId === "REP-1")).toBe(true); });
  it("includes authorized subordinate records", () => expect(scopeSampleReportData(dataset(), ["MGR-1", "REP-1"]).requests).toHaveLength(1));
  it("cannot widen scope using an unauthorized rep filter", () => { const scoped = scopeSampleReportData(dataset(), ["REP-1"]); expect(buildSampleRequestLifecycleReport(scoped, { repId: "REP-2" })).toEqual([]); });
  it("does not use legacy names to drive totals", () => { const legacy = { ...allocation(), productName: "WRONG", repName: "WRONG", originalQuota: 9999 } as SampleAllocation; expect(buildRepresentativeBalanceReport(dataset({ allocations: [legacy] }))[0].currentRemaining).toBe(8); });
});
