import type { User as FirebaseUser } from "firebase/auth";
import type { Role, SupervisorCoachingAppraisal, SupervisorIdentityPresentation, SupervisorVisit, SupervisorVisitCustomerType } from "../types";
import type { AppraisalCreate, AppraisalDraftSave, AppraisalFinalRepresentativeReview, AppraisalKeepUnchanged, AppraisalRepresentativeReview, AppraisalRevisionSave, SupervisorVisitCreate } from "../../server/supervisorVisitService";

async function call<T>(user: Pick<FirebaseUser, "getIdToken">, path: string, body: unknown, fetcher: typeof fetch = fetch): Promise<T> {
  const token = await user.getIdToken(); const response = await fetcher(path, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json();
  if (!response.ok) { const error = new Error(result?.code || "Supervisor visit request failed") as Error & { code?: string }; error.code = result?.code; throw error; } return result as T;
}
export const createSupervisorVisitRecord = (user: Pick<FirebaseUser,"getIdToken">, input: SupervisorVisitCreate) => call<{success: true; visit: SupervisorVisit; replayed:boolean}>(user, "/api/supervisor-visits/create", input);
export const transitionSupervisorVisitRecord = (user:Pick<FirebaseUser,"getIdToken">,input:{visitId:string;action:"START"|"COMPLETE"|"CANCEL";outcome?:string;notes?:string}) => call<{success:true;visit:SupervisorVisit}>(user,"/api/supervisor-visits/transition",input);
export const rescheduleSupervisorVisitRecord = (user:Pick<FirebaseUser,"getIdToken">,input:{visitId:string;plannedDate:string;plannedTime:string}) => call<{success:true;visit:SupervisorVisit}>(user,"/api/supervisor-visits/reschedule",input);
export interface SupervisorVisitAreaOption { id:string;name:string;countryId:string;countryName:string;districtId:string;districtName:string;cityId:string;cityName:string }
export const fetchSupervisorVisitOptions = (user: Pick<FirebaseUser,"getIdToken">) => call<{authorized:true;areas:SupervisorVisitAreaOption[]}>(user,"/api/supervisor-visits/options",{});
export const fetchEligibleSupervisorRepresentatives = (user: Pick<FirebaseUser,"getIdToken">, input: {customerType:SupervisorVisitCustomerType;customerId:string;areaId:string}) => call<{authorized:true;representatives:Array<{id:string;name:string;role:Role}>}>(user,"/api/supervisor-visits/eligible-representatives",input);
export const fetchSupervisorVisits = (user: Pick<FirebaseUser,"getIdToken">, filter: {customerType?: SupervisorVisitCustomerType; customerId?: string; supervisorRole?: Role.MEDICAL_SUPERVISOR|Role.SALES_SUPERVISOR} = {}) => call<{authorized: true; visits: SupervisorVisit[]}>(user, "/api/supervisor-visits/scoped-query", filter);
export const fetchSupervisorCustomerVisitHistory = (user: Pick<FirebaseUser,"getIdToken">, input: {customerType:SupervisorVisitCustomerType;customerId:string;supervisorRole?:Role.MEDICAL_SUPERVISOR|Role.SALES_SUPERVISOR}) => call<{authorized:true;visits:SupervisorVisit[];areas:SupervisorVisitAreaOption[];supervisors:Record<string,SupervisorIdentityPresentation>}>(user,"/api/supervisor-visits/customer-history",input);
export const createSupervisorAppraisalRecord = (user: Pick<FirebaseUser,"getIdToken">, input: AppraisalCreate) => call<{success: true; appraisal: SupervisorCoachingAppraisal}>(user, "/api/supervisor-coaching/create", input);
export const saveSupervisorAppraisalDraftRecord=(user:Pick<FirebaseUser,"getIdToken">,input:AppraisalDraftSave)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/save-draft",input);
export const submitSupervisorAppraisalRecord=(user:Pick<FirebaseUser,"getIdToken">,appraisalId:string,expectedWorkflowVersion:number)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/submit",{appraisalId,expectedWorkflowVersion});
export const reviewSupervisorAppraisalRecord=(user:Pick<FirebaseUser,"getIdToken">,input:AppraisalRepresentativeReview)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/review",input);
export const keepSupervisorAppraisalUnchangedRecord=(user:Pick<FirebaseUser,"getIdToken">,input:AppraisalKeepUnchanged)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/keep-unchanged",input);
export const openSupervisorAppraisalRevisionRecord=(user:Pick<FirebaseUser,"getIdToken">,appraisalId:string,expectedWorkflowVersion:number)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/open-revision",{appraisalId,expectedWorkflowVersion});
export const saveSupervisorAppraisalRevisionRecord=(user:Pick<FirebaseUser,"getIdToken">,input:AppraisalRevisionSave)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/save-revision",input);
export const submitSupervisorAppraisalRevisionRecord=(user:Pick<FirebaseUser,"getIdToken">,appraisalId:string,expectedWorkflowVersion:number)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/submit-revision",{appraisalId,expectedWorkflowVersion});
export const finalReviewSupervisorAppraisalRecord=(user:Pick<FirebaseUser,"getIdToken">,input:AppraisalFinalRepresentativeReview)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/final-review",input);
export const signOffSupervisorAppraisalRecord=(user:Pick<FirebaseUser,"getIdToken">,appraisalId:string,expectedWorkflowVersion:number)=>call<{success:true;appraisal:SupervisorCoachingAppraisal}>(user,"/api/supervisor-coaching/sign-off",{appraisalId,expectedWorkflowVersion});
export const fetchSupervisorAppraisals = (user: Pick<FirebaseUser,"getIdToken">) => call<{authorized: true; appraisals: SupervisorCoachingAppraisal[];visits:Record<string,SupervisorVisit>;supervisors:Record<string,SupervisorIdentityPresentation>}>(user, "/api/supervisor-coaching/scoped-query", {});
