import { describe, expect, it } from "vitest";
import { Role } from "../../types";
import { applyOrderTransitionWithTemplate, canTransitionOrderWithTemplate, ENTERPRISE_WORKFLOW_TEMPLATE, type OrderWorkflowTemplate } from "./orderWorkflowTemplate";

const consolidated: OrderWorkflowTemplate = { ...ENTERPRISE_WORKFLOW_TEMPLATE, templateId: "CONSOLIDATED", name: "Consolidated internal processing", stages: ENTERPRISE_WORKFLOW_TEMPLATE.stages.map(stage => ["FINANCE_REVIEW", "OPERATIONS_REVIEW", "STORE_PREPARATION"].includes(stage.stage) ? { ...stage, allowedRoles: [Role.ORDER_OPS_OFFICER, Role.FINANCE, Role.STORE_MANAGER] } : stage) };
const actor = { uid: "PROCESSOR", role: Role.ORDER_OPS_OFFICER, name: "Internal Processor" };

describe("WP77E configurable order workflow engine", () => {
  it("preserves separated enterprise staffing", () => { expect(canTransitionOrderWithTemplate({ order: { id: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "REP" }, action: "FINANCE_APPROVE", actor, template: ENTERPRISE_WORKFLOW_TEMPLATE }).allowed).toBe(false); expect(canTransitionOrderWithTemplate({ order: { id: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "REP" }, action: "FINANCE_APPROVE", actor: { ...actor, role: Role.FINANCE }, template: ENTERPRISE_WORKFLOW_TEMPLATE }).allowed).toBe(true); });
  it("allows a configured internal processor to execute multiple stages", () => { const finance = applyOrderTransitionWithTemplate({ order: { id: "O", displayNumber: "SO", status: "PENDING_FINANCE_REVIEW", createdByUid: "REP", history: [] }, action: "FINANCE_APPROVE", actor, template: consolidated, source: "BACKEND" }); expect(finance.success).toBe(true); const operations = applyOrderTransitionWithTemplate({ order: finance.updatedOrder, action: "OPERATIONS_APPROVE", actor, template: consolidated, source: "BACKEND" }); expect(operations.success).toBe(true); const store = applyOrderTransitionWithTemplate({ order: operations.updatedOrder, action: "STORE_START_PREPARE", actor, template: consolidated, source: "BACKEND" }); expect(store.success).toBe(true); expect(store.updatedOrder.history).toHaveLength(3); expect(store.updatedOrder.history.map((event: any) => event.action)).toEqual(["FINANCE_APPROVE", "OPERATIONS_APPROVE", "STORE_START_PREPARE"]); });
  it("never lets a template bypass creator segregation", () => expect(canTransitionOrderWithTemplate({ order: { id: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "PROCESSOR" }, action: "FINANCE_APPROVE", actor, template: consolidated }).reasonCode).toBe("SEGREGATION_OF_DUTIES_VIOLATION"));
  it("fails closed for inactive templates and unlisted roles", () => { expect(canTransitionOrderWithTemplate({ order: { id: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "REP" }, action: "FINANCE_APPROVE", actor, template: { ...consolidated, active: false } }).allowed).toBe(false); expect(canTransitionOrderWithTemplate({ order: { id: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "REP" }, action: "FINANCE_APPROVE", actor: { ...actor, role: Role.DELIVERY_OFFICER }, template: consolidated }).allowed).toBe(false); });
});
