export const UAT_PROJECT_ID = "demo-menareps-uat";
export const UAT_CERTIFIED_COMMIT = "0915da491745a474e3e826c069d0f3a8a5592a5b";
export const UAT_RULES_CANDIDATE = "FIX5_HOTSPOT_SECURITY_CANDIDATE";
export const UAT_RULE_HASHES = Object.freeze({
  firestore: "2b94069b867b7969d6f638a74176b89239b13da407df69c6b44e8099c3185217",
  storage: "21779045cd7421a7610259eb8ed5ba1770a46949e6186eb87fa7b1e12d804416",
});
export const UAT_ENDPOINTS = Object.freeze({
  auth: "127.0.0.1:9099",
  firestore: "127.0.0.1:8089",
  storage: "127.0.0.1:9199",
  frontend: "127.0.0.1:4178",
  backend: "127.0.0.1:5008",
});
export const UAT_ADMIN_STORAGE_ENDPOINT = `http://${UAT_ENDPOINTS.storage}`;
export const UAT_BASE_URL = `http://${UAT_ENDPOINTS.frontend}`;
export const UAT_STORAGE_BUCKET = `${UAT_PROJECT_ID}.appspot.com`;

export function uatEnvironment(runSecret: string): NodeJS.ProcessEnv {
  return {
    GCLOUD_PROJECT: UAT_PROJECT_ID,
    GOOGLE_CLOUD_PROJECT: UAT_PROJECT_ID,
    FIREBASE_PROJECT_ID: UAT_PROJECT_ID,
    FIRESTORE_DATABASE_ID: "(default)",
    FIREBASE_CONFIG: JSON.stringify({ projectId: UAT_PROJECT_ID, storageBucket: UAT_STORAGE_BUCKET }),
    FIREBASE_AUTH_EMULATOR_HOST: UAT_ENDPOINTS.auth,
    FIRESTORE_EMULATOR_HOST: UAT_ENDPOINTS.firestore,
    FIREBASE_STORAGE_EMULATOR_HOST: UAT_ENDPOINTS.storage,
    STORAGE_EMULATOR_HOST: UAT_ADMIN_STORAGE_ENDPOINT,
    VITE_MENAREPS_EMULATOR_MODE: "true",
    VITE_FIREBASE_PROJECT_ID: UAT_PROJECT_ID,
    VITE_FIREBASE_AUTH_DOMAIN: `${UAT_PROJECT_ID}.firebaseapp.com`,
    VITE_FIREBASE_STORAGE_BUCKET: UAT_STORAGE_BUCKET,
    VITE_FIREBASE_FIRESTORE_DATABASE_ID: "(default)",
    VITE_FIREBASE_AUTH_EMULATOR_URL: `http://${UAT_ENDPOINTS.auth}`,
    VITE_FIRESTORE_EMULATOR_HOST: UAT_ENDPOINTS.firestore,
    VITE_FIREBASE_STORAGE_EMULATOR_HOST: UAT_ENDPOINTS.storage,
    MENAREPS_UAT_RUN_SECRET: runSecret,
  };
}
