import React, { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Eye, Search, Star, Users, X } from "lucide-react";
import { auth } from "../../lib/firebase";
import { fetchSupervisorAppraisals, finalReviewSupervisorAppraisalRecord, keepSupervisorAppraisalUnchangedRecord, openSupervisorAppraisalRevisionRecord, reviewSupervisorAppraisalRecord, saveSupervisorAppraisalRevisionRecord, signOffSupervisorAppraisalRecord, submitSupervisorAppraisalRevisionRecord } from "../../lib/supervisorVisitClient";
import { supervisorIdentityPresentation, supervisorPresentationLabel } from "../../lib/supervisorVisitPresentation";
import { Role, type Pharmacy, type Physician, type SupervisorCoachingAppraisal, type SupervisorCoachingFinalReviewDecision, type SupervisorCoachingReviewDecision, type SupervisorCoachingWorkflowPhase, type SupervisorIdentityPresentation, type SupervisorVisit, type User } from "../../types";

const words=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
const finalStatus=(status:string)=>["SIGNED_OFF","VOID","COMPLETED"].includes(status);
const versionOf=(a:SupervisorCoachingAppraisal)=>a.workflowVersion??0;
function phaseOf(a:SupervisorCoachingAppraisal):SupervisorCoachingWorkflowPhase|null{
 if(a.workflowPhase)return a.workflowPhase;if(a.status==="SIGNED_OFF")return"FINALIZED";if(a.status==="VOID")return"VOID";if(a.status==="COMPLETED")return null;
 if(a.status==="DRAFT")return a.preRevisionSnapshot&&a.revisionCount===1?"REVISION_DRAFT":!a.representativeReviewDecision?"INITIAL_DRAFT":null;
 if(a.status==="PENDING_CONFIRMATION")return a.preRevisionSnapshot&&a.revisionCount===1?"FINAL_REPRESENTATIVE_REVIEW":"INITIAL_REPRESENTATIVE_REVIEW";
 if(a.status==="REPRESENTATIVE_REVIEWED"){if(a.finalRepresentativeReviewDecision||a.representativeReviewDecision==="ACKNOWLEDGED"||a.supervisorDisagreementResolution==="KEEP_UNCHANGED")return"SUPERVISOR_FINAL_REVIEW";if(a.representativeReviewDecision==="DISAGREE_REQUEST_REVIEW"&&!a.supervisorDisagreementResolution)return"SUPERVISOR_DISAGREEMENT_REVIEW";}
 return null;
}

export default function CoachingReports({lang,currentUser,users,physicians,pharmacies}:{lang:"en"|"ar";currentUser:User;users:User[];physicians:Physician[];pharmacies:Pharmacy[]}){
 const isRtl=lang==="ar",representative=[Role.MEDICAL_REP,Role.SALES_REP].includes(currentUser.role),[reports,setReports]=useState<SupervisorCoachingAppraisal[]>([]),[visits,setVisits]=useState<Record<string,SupervisorVisit>>({}),[supervisors,setSupervisors]=useState<Record<string,SupervisorIdentityPresentation>>({}),[error,setError]=useState(""),[search,setSearch]=useState(""),[repFilter,setRepFilter]=useState("ALL"),[statusFilter,setStatusFilter]=useState("ALL"),[typeFilter,setTypeFilter]=useState("ALL"),[selected,setSelected]=useState<SupervisorCoachingAppraisal|null>(null);
 const [reviewDecision,setReviewDecision]=useState<SupervisorCoachingReviewDecision>("ACKNOWLEDGED"),[finalDecision,setFinalDecision]=useState<SupervisorCoachingFinalReviewDecision>("ACKNOWLEDGE_REVISED_APPRAISAL"),[representativeComment,setRepresentativeComment]=useState(""),[supervisorRationale,setSupervisorRationale]=useState("");
 const [scores,setScores]=useState<Record<string,number>>({}),[comments,setComments]=useState<Record<string,string>>({}),[sectionNotes,setSectionNotes]=useState<Record<string,string>>({}),[strengths,setStrengths]=useState(""),[improvementAreas,setImprovementAreas]=useState(""),[actionPlan,setActionPlan]=useState(""),[recommendations,setRecommendations]=useState("");
 const load=()=>{if(!auth.currentUser)return Promise.resolve();return fetchSupervisorAppraisals(auth.currentUser).then(r=>{setReports(r.appraisals);setVisits(r.visits);setSupervisors(r.supervisors);setError("")}).catch(e=>{setReports([]);setVisits({});setSupervisors({});setError(e instanceof Error?e.message:"Unable to load coaching reports")})};
 useEffect(()=>{void load()},[]);
 const select=(a:SupervisorCoachingAppraisal)=>{setSelected(a);setScores(a.scores);setComments(a.comments);setSectionNotes(a.sectionNotes||{});setStrengths(a.strengths);setImprovementAreas(a.improvementAreas);setActionPlan(a.actionPlan);setRecommendations(a.recommendations);setRepresentativeComment("");setSupervisorRationale("")};
 const replace=async(a:SupervisorCoachingAppraisal)=>{select(a);await load()};
 const act=async(run:()=>Promise<{appraisal:SupervisorCoachingAppraisal}>,fallback:string)=>{try{await replace((await run()).appraisal)}catch(e){setError(e instanceof Error?e.message:fallback)}};
 const firstReview=()=>auth.currentUser&&selected?act(()=>reviewSupervisorAppraisalRecord(auth.currentUser!,{appraisalId:selected.id,expectedWorkflowVersion:versionOf(selected),reviewDecision,representativeComment}),"Unable to submit review"):undefined;
 const finalReview=()=>auth.currentUser&&selected?act(()=>finalReviewSupervisorAppraisalRecord(auth.currentUser!,{appraisalId:selected.id,expectedWorkflowVersion:versionOf(selected),reviewDecision:finalDecision,representativeComment}),"Unable to submit final review"):undefined;
 const keep=()=>auth.currentUser&&selected&&supervisorRationale.trim()?act(()=>keepSupervisorAppraisalUnchangedRecord(auth.currentUser!,{appraisalId:selected.id,expectedWorkflowVersion:versionOf(selected),supervisorRationale}),"Unable to keep appraisal unchanged"):undefined;
 const openRevision=()=>auth.currentUser&&selected?act(()=>openSupervisorAppraisalRevisionRecord(auth.currentUser!,selected.id,versionOf(selected)),"Unable to open revision"):undefined;
 const revisionFields=()=>({scores,comments,sectionNotes,strengths,improvementAreas,actionPlan,recommendations,overallRating:weighted(selected!,scores)});
 const saveRevision=()=>auth.currentUser&&selected?act(()=>saveSupervisorAppraisalRevisionRecord(auth.currentUser!,{appraisalId:selected.id,expectedWorkflowVersion:versionOf(selected),...revisionFields()}),"Unable to save revision"):undefined;
 const submitRevision=async()=>{if(!auth.currentUser||!selected)return;try{const saved=await saveSupervisorAppraisalRevisionRecord(auth.currentUser,{appraisalId:selected.id,expectedWorkflowVersion:versionOf(selected),...revisionFields()}),submitted=await submitSupervisorAppraisalRevisionRecord(auth.currentUser,saved.appraisal.id,versionOf(saved.appraisal));await replace(submitted.appraisal)}catch(e){setError(e instanceof Error?e.message:"Unable to submit revision")}};
 const signOff=()=>auth.currentUser&&selected?act(()=>signOffSupervisorAppraisalRecord(auth.currentUser!,selected.id,versionOf(selected)),"Unable to sign off"):undefined;
 const repName=(id:string)=>users.find(u=>u.id===id)?.name||(isRtl?"مندوب غير معروف":"Unknown representative"),supervisorIdentity=(id:string)=>supervisorIdentityPresentation(supervisors[id],lang),customerName=(id:string)=>[...physicians,...pharmacies].find(c=>c.id===id)?.name||id;
 const reps=useMemo(()=>Array.from(new Set<string>(reports.map(r=>r.representativeId))).map(id=>({id,name:repName(id)})),[reports,users]);
 const filtered=useMemo(()=>reports.filter(r=>{const haystack=`${r.id} ${repName(r.representativeId)} ${customerName(r.customerId)} ${r.appraisalType} ${r.strengths} ${r.improvementAreas}`.toLowerCase();return(!search||haystack.includes(search.toLowerCase()))&&(repFilter==="ALL"||r.representativeId===repFilter)&&(statusFilter==="ALL"||r.status===statusFilter)&&(typeFilter==="ALL"||r.appraisalType===typeFilter)}).sort((a,b)=>b.visitDate.localeCompare(a.visitDate)),[reports,search,repFilter,statusFilter,typeFilter]);
 const signed=reports.filter(r=>["SIGNED_OFF","COMPLETED"].includes(r.status)).length,pending=reports.filter(r=>r.status==="PENDING_CONFIRMATION").length,average=reports.length?reports.reduce((n,r)=>n+r.overallRating,0)/reports.length:0;
 const t={title:isRtl?"تقارير التوجيه ونماذج التقييم":"Coaching Reports & Appraisal Forms",search:isRtl?"ابحث بالمندوب أو العميل أو التقييم...":"Search representative, customer or appraisal...",all:isRtl?"الكل":"All",rep:isRtl?"المندوب":"Representative",status:isRtl?"الحالة":"Status",type:isRtl?"نوع التقييم":"Appraisal Type",score:isRtl?"التقييم":"Score",customer:isRtl?"العميل":"Customer",details:isRtl?"التفاصيل":"Details"};
 const phase=selected?phaseOf(selected):null,revisionEditing=!representative&&phase==="REVISION_DRAFT";
 return <div className="space-y-5 min-w-0" dir={isRtl?"rtl":"ltr"} id="coaching-reports-root">
  <style>{`@media(max-width:767px){#coaching-reports-root section:has(>table){display:none}}`}</style>
  <header className="bg-white dark:bg-slate-900 border rounded-2xl p-4 sm:p-6"><h1 className="text-xl font-bold">{t.title}</h1><p className="text-xs text-slate-500 mt-1">{representative?(isRtl?"مراجعة تقييماتك المرتبطة فقط":"Review only your linked coaching appraisals"):(isRtl?"مراجعة وإغلاق تقييمات فريقك":"Review and finalize your team coaching appraisals")}</p></header>
  <section className="grid grid-cols-1 sm:grid-cols-4 gap-3"><Kpi icon={<Users/>} label={isRtl?"إجمالي التقييمات":"Total Appraisals"} value={reports.length}/><Kpi icon={<Star/>} label={isRtl?"متوسط التقييم":"Average Rating"} value={reports.length?`${average.toFixed(1)} / 5`:"—"}/><Kpi icon={<Activity/>} label={isRtl?"معتمد":"Signed Off"} value={signed}/><Kpi icon={<BarChart3/>} label={isRtl?"بانتظار المراجعة":"Pending Confirmation"} value={pending}/></section>
  <section className="bg-white dark:bg-slate-900 border rounded-xl p-4"><div className="grid md:grid-cols-5 gap-2"><div className="relative md:col-span-2"><Search size={14} className="absolute start-3 top-3.5 text-slate-400"/><input aria-label={t.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="min-h-11 w-full border rounded-lg py-2 ps-9 pe-3 text-xs bg-transparent"/></div>{!representative&&<Select label={t.rep} value={repFilter} set={setRepFilter} options={[{id:"ALL",name:t.all},...reps]}/>}<Select label={t.type} value={typeFilter} set={setTypeFilter} options={[{id:"ALL",name:t.all},{id:"MEDICAL",name:"Medical"},{id:"SALES",name:"Sales"}]}/><Select label={t.status} value={statusFilter} set={setStatusFilter} options={[{id:"ALL",name:t.all},...["DRAFT","PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED","SIGNED_OFF","VOID","COMPLETED"].map(id=>({id,name:statusLabel(id,isRtl)}))]}/></div></section>
  {error&&<div role="alert" className="bg-rose-50 text-rose-700 p-3 rounded-lg text-xs">{error}</div>}
  <section className="bg-white dark:bg-slate-900 border rounded-xl p-4"><h2 className="text-xs font-bold mb-3">{isRtl?"اتجاه درجات التقييم الأخيرة":"Recent Appraisal Score Trend"}</h2><div className="flex items-end gap-2 h-24" aria-label="Recent appraisal scores">{filtered.slice(0,12).reverse().map(r=><div key={r.id} title={`${r.id}: ${r.overallRating}`} className="flex-1 min-w-2 bg-blue-500 rounded-t" style={{height:`${Math.max(4,r.overallRating/5*100)}%`}}/>)}</div></section>
  <section className="bg-white dark:bg-slate-900 border rounded-xl overflow-x-auto"><table className="w-full min-w-[900px] text-xs"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{["ID",t.type,t.rep,t.customer,isRtl?"المخطط":"Planned",isRtl?"الفعلي":"Actual",t.score,t.status,t.details].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-mono font-bold">{r.id}</td><td className="p-3">{r.appraisalType}</td><td className="p-3">{repName(r.representativeId)}</td><td className="p-3">{customerName(r.customerId)}</td><td className="p-3">{planned(visits[r.supervisorVisitId],r)}</td><td className="p-3">{actual(visits[r.supervisorVisitId])}</td><td className="p-3 font-bold text-blue-600">{r.overallRating.toFixed(2)} / 5</td><td className="p-3"><Status value={r.status} isRtl={isRtl}/></td><td className="p-3"><button onClick={()=>select(r)} className="min-h-11 px-3"><Eye size={16}/></button></td></tr>)}</tbody></table>{!filtered.length&&!error&&<p className="p-12 text-center text-xs text-slate-400">No coaching appraisals match the current filters.</p>}</section>
  <section className="grid gap-3 md:hidden">{filtered.map(r=><article key={r.id} className="bg-white dark:bg-slate-900 border rounded-xl p-4 space-y-2"><div className="flex justify-between gap-2"><strong className="font-mono text-xs">{r.id}</strong><Status value={r.status} isRtl={isRtl}/></div><p className="text-xs font-bold">{customerName(r.customerId)}</p><p className="text-xs text-slate-500">{repName(r.representativeId)} • {planned(visits[r.supervisorVisitId],r)}</p><button type="button" onClick={()=>select(r)} className="min-h-11 w-full border rounded-lg text-xs font-bold">{t.details}</button></article>)}</section>
  {selected&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] bg-slate-950/60 p-4 flex items-center justify-center"><div className="bg-white dark:bg-slate-900 border rounded-2xl w-full max-w-5xl max-h-[92vh] overflow-auto"><header className="sticky top-0 z-10 bg-white dark:bg-slate-900 border-b p-5 flex justify-between"><div><h2 className="font-bold text-lg">{selected.appraisalType} Appraisal</h2><p className="text-xs text-slate-500">{selected.id} • {statusLabel(selected.status,isRtl)} • {supervisorPresentationLabel(phase||"LEGACY_FINAL",lang)}</p></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="p-5 space-y-4">
   <div className="grid sm:grid-cols-3 gap-3"><Detail label="Supervisor" value={supervisorIdentity(selected.supervisorId)}/><Detail label="Representative" value={repName(selected.representativeId)}/><Detail label="Customer" value={customerName(selected.customerId)}/><Detail label="Planned" value={planned(visits[selected.supervisorVisitId],selected)}/><Detail label="Actual" value={actual(visits[selected.supervisorVisitId])}/><Detail label="Status" value={statusLabel(selected.status,isRtl)}/></div>
   {selected.preRevisionSnapshot&&<div className="border rounded-xl p-4 bg-amber-50 dark:bg-amber-950/20 text-xs"><strong>Revision 1 of 1</strong><p className="mt-1">The immutable original evaluation is preserved. Original submission: {selected.preRevisionSnapshot.originalSubmittedAt||"—"}</p></div>}
   {selected.sections.map(section=><section key={section.id} className="border rounded-xl p-4"><div className="flex justify-between"><strong>{section.title}</strong><span className="text-xs text-slate-500">Weight {selected.sectionWeights?.[section.id]??"—"}% (read-only)</span></div>{section.criteria.map(id=><div key={id} className="grid sm:grid-cols-[1fr_110px] gap-2 border-t mt-3 pt-3"><div><p className="font-bold text-xs">{words(id)}</p>{revisionEditing?<textarea value={comments[id]||""} onChange={e=>setComments(v=>({...v,[id]:e.target.value}))} className="w-full mt-1 border rounded-lg p-2 text-xs"/>:<p className="text-xs text-slate-500 whitespace-pre-wrap">{selected.comments[id]||"—"}</p>}</div>{revisionEditing?<select value={scores[id]||""} onChange={e=>setScores(v=>({...v,[id]:Number(e.target.value)}))} className="border rounded-lg p-2"><option value="">—</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select>:<strong className="text-blue-600">{selected.scores[id]===undefined?"—":`${selected.scores[id]} / 5`}</strong>}</div>)}{revisionEditing?<textarea value={sectionNotes[section.id]||""} onChange={e=>setSectionNotes(v=>({...v,[section.id]:e.target.value}))} placeholder="Section notes" className="w-full mt-3 border rounded-lg p-2 text-xs"/>:selected.sectionNotes?.[section.id]&&<p className="text-xs mt-3 whitespace-pre-wrap">{selected.sectionNotes[section.id]}</p>}</section>)}
   <div className="grid md:grid-cols-2 gap-3">{revisionEditing?<><EditCard label="Strengths" value={strengths} set={setStrengths}/><EditCard label="Improvement Areas" value={improvementAreas} set={setImprovementAreas}/><EditCard label="Action Plan" value={actionPlan} set={setActionPlan}/><EditCard label="Recommendations" value={recommendations} set={setRecommendations}/></>:<><TextCard label="Strengths" value={selected.strengths}/><TextCard label="Improvement Areas" value={selected.improvementAreas}/><TextCard label="Action Plan" value={selected.actionPlan}/><TextCard label="Recommendations" value={selected.recommendations}/></>}</div>
   {selected.representativeReviewDecision&&<div className="border rounded-xl p-4"><Detail label="Original Representative Decision" value={supervisorPresentationLabel(selected.representativeReviewDecision,lang)}/><p className="text-xs mt-2 whitespace-pre-wrap">{selected.representativeComment||"—"}</p></div>}
   {selected.supervisorDisagreementResolution&&<div className="border rounded-xl p-4"><Detail label="Supervisor Resolution" value={supervisorPresentationLabel(selected.supervisorDisagreementResolution,lang)}/>{selected.supervisorDisagreementRationale&&<p className="text-xs mt-2 whitespace-pre-wrap">{selected.supervisorDisagreementRationale}</p>}</div>}
   {selected.finalRepresentativeReviewDecision&&<div className="border rounded-xl p-4"><Detail label="Final Representative Decision" value={supervisorPresentationLabel(selected.finalRepresentativeReviewDecision,lang)}/><p className="text-xs mt-2 whitespace-pre-wrap">{selected.finalRepresentativeComment||"—"}</p></div>}
   {representative&&phase==="INITIAL_REPRESENTATIVE_REVIEW"&&<ReviewPanel value={reviewDecision} set={v=>setReviewDecision(v as SupervisorCoachingReviewDecision)} options={["ACKNOWLEDGED","DISAGREE_REQUEST_REVIEW"]} comment={representativeComment} setComment={setRepresentativeComment} submit={firstReview} label="Submit First Review" lang={lang}/>}
   {representative&&phase==="FINAL_REPRESENTATIVE_REVIEW"&&<ReviewPanel value={finalDecision} set={v=>setFinalDecision(v as SupervisorCoachingFinalReviewDecision)} options={["ACKNOWLEDGE_REVISED_APPRAISAL"]} comment={representativeComment} setComment={setRepresentativeComment} submit={finalReview} label="Submit Final Review" lang={lang}/>}
   {!representative&&phase==="SUPERVISOR_DISAGREEMENT_REVIEW"&&<div className="border rounded-xl p-4 space-y-3"><textarea value={supervisorRationale} onChange={e=>setSupervisorRationale(e.target.value)} placeholder="Mandatory rationale to keep unchanged" className="w-full border rounded-lg p-3"/><div className="flex gap-2"><button onClick={keep} disabled={!supervisorRationale.trim()} className="border border-blue-600 text-blue-700 rounded-lg px-4 min-h-11 disabled:opacity-50 disabled:cursor-not-allowed">Keep Appraisal Unchanged</button><button onClick={openRevision} className="bg-amber-600 text-white rounded-lg px-4 min-h-11">Revise Appraisal</button></div></div>}
   {revisionEditing&&<div className="flex justify-end gap-2"><button onClick={saveRevision} className="border border-blue-600 text-blue-700 rounded-lg px-4 min-h-11">Save Revision</button><button onClick={()=>void submitRevision()} className="bg-blue-700 text-white rounded-lg px-4 min-h-11">Submit Revision for Final Review</button></div>}
   {!representative&&phase==="SUPERVISOR_FINAL_REVIEW"&&<button onClick={signOff} className="bg-emerald-700 text-white rounded-lg px-4 min-h-11">Final Sign-off</button>}
   {selected.status==="VOID"&&<div className="p-3 rounded-xl bg-slate-100 text-xs font-bold">VOID — {selected.voidReason}</div>}{finalStatus(selected.status)&&<p className="text-xs text-slate-500">This appraisal is final and read-only.</p>}
  </div></div></div>}
 </div>;
}

function weighted(a:SupervisorCoachingAppraisal,scores:Record<string,number>){let sum=0,total=0;for(const section of a.sections){const values=section.criteria.map(id=>scores[id]).filter(Number.isFinite);if(!values.length)continue;const weight=a.sectionWeights?.[section.id]||0;sum+=(values.reduce((x,y)=>x+y,0)/values.length)*weight;total+=weight}return total?Number((sum/total).toFixed(2)):0}
function ReviewPanel({value,set,options,comment,setComment,submit,label,lang}:{value:string;set:(v:string)=>void;options:string[];comment:string;setComment:(v:string)=>void;submit:()=>unknown;label:string;lang:"en"|"ar"}){return <div className="border rounded-xl p-4 space-y-3"><select value={value} onChange={e=>set(e.target.value)} className="w-full border rounded-lg p-2">{options.map(x=><option key={x} value={x}>{supervisorPresentationLabel(x,lang)}</option>)}</select><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Representative comment" className="w-full border rounded-lg p-3"/><button onClick={submit} className="bg-blue-700 text-white rounded-lg px-4 min-h-11">{label}</button></div>}
function planned(visit:SupervisorVisit|undefined,appraisal:SupervisorCoachingAppraisal){return visit?.plannedDate?`${visit.plannedDate} ${visit.plannedTime||"—"} ${visit.planningTimezone||""}`.trim():`${appraisal.visitDate} (historical fallback)`}
function actual(visit?:SupervisorVisit){return visit?`${visit.startedAt||"—"} → ${visit.completedAt||"—"}`:"—"}
function statusLabel(value:string,isRtl:boolean){if(value==="COMPLETED"||value==="SIGNED_OFF")return isRtl?"معتمد":"Signed Off";if(value==="PENDING_CONFIRMATION")return isRtl?"بانتظار التأكيد":"Pending Confirmation";if(value==="REPRESENTATIVE_REVIEWED")return isRtl?"تمت مراجعة المندوب":"Representative Reviewed";if(value==="VOID")return isRtl?"ملغى":"Void";return isRtl?"مسودة":"Draft"}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="bg-white dark:bg-slate-900 border rounded-xl p-4 flex gap-3 items-center"><span className="text-blue-600">{icon}</span><div><p className="text-[9px] uppercase font-bold text-slate-400">{label}</p><strong className="text-xl">{value}</strong></div></div>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Array<{id:string;name:string}>}){return <select aria-label={label} value={value} onChange={e=>set(e.target.value)} className="min-h-11 w-full border rounded-lg px-2 text-xs bg-transparent">{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}
function Status({value,isRtl}:{value:string;isRtl:boolean}){return <span className="px-2 py-1 rounded text-[10px] font-bold bg-slate-100 text-slate-700">{statusLabel(value,isRtl)}</span>}
function Detail({label,value}:{label:string;value:string}){return <div><p className="text-[9px] uppercase font-bold text-slate-400">{label}</p><p className="text-xs font-semibold mt-1 break-words">{value}</p></div>}
function TextCard({label,value}:{label:string;value:string}){return <div className="border rounded-xl p-4"><h3 className="text-xs font-bold">{label}</h3><p className="text-xs mt-2 whitespace-pre-wrap">{value||"—"}</p></div>}
function EditCard({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="border rounded-xl p-4 text-xs font-bold">{label}<textarea value={value} onChange={e=>set(e.target.value)} className="w-full mt-2 border rounded-lg p-2"/></label>}
