import React, { useEffect, useState } from "react";
import { auth } from "../../lib/firebase";
import { fetchSupervisorCustomerVisitHistory, type SupervisorVisitAreaOption } from "../../lib/supervisorVisitClient";
import { supervisorHistoryErrorMessage, supervisorIdentityPresentation, supervisorPresentationLabel } from "../../lib/supervisorVisitPresentation";
import { Role, type SupervisorIdentityPresentation, type SupervisorVisit, type SupervisorVisitCustomerType, type User } from "../../types";

export default function SupervisorVisitHistory({ customerType, customerId, supervisorRole, lang="en" }: { customerType:SupervisorVisitCustomerType; customerId:string; supervisorRole?:Role.MEDICAL_SUPERVISOR|Role.SALES_SUPERVISOR; users?:User[];lang?:"en"|"ar" }) {
 const isRtl=lang==="ar",[visits,setVisits]=useState<SupervisorVisit[]>([]),[areas,setAreas]=useState<SupervisorVisitAreaOption[]>([]),[supervisors,setSupervisors]=useState<Record<string,SupervisorIdentityPresentation>>({}),[error,setError]=useState(""); useEffect(()=>{if(!auth.currentUser)return;void fetchSupervisorCustomerVisitHistory(auth.currentUser,{customerType,customerId,supervisorRole}).then(result=>{setVisits(result.visits);setAreas(result.areas);setSupervisors(result.supervisors);setError("")}).catch(e=>{const code=e&&typeof e==="object"&&"code" in e?String(e.code):undefined;console.warn("[SupervisorVisitHistory] Read denied or failed",{code,customerType,customerId});setVisits([]);setAreas([]);setSupervisors({});setError(supervisorHistoryErrorMessage(code,lang))})},[customerType,customerId,supervisorRole,lang]);
 const geography=(visit:SupervisorVisit)=>{const area=areas.find(row=>row.id===visit.areaId);return area?`${area.countryName} / ${area.districtName} / ${area.cityName} / ${area.name}`:`${visit.countryId} / ${visit.districtId} / ${visit.cityId} / ${visit.areaId}`};
 const projectedRole=(id:string)=>{const identity=supervisors[id];return identity?.resolved&&identity.role?supervisorPresentationLabel(identity.role,lang):"—"};
 if(error)return <p className="p-6 text-xs text-rose-600" role="alert">{error}</p>; if(!visits.length)return <p className="p-10 text-center text-xs text-slate-400">{isRtl?"لا توجد زيارات مشرف مسجلة.":"No supervisor visits recorded."}</p>;
 const headers=isRtl?["رمز الزيارة","التاريخ المخطط","الوقت المخطط","البدء الفعلي","الإكمال الفعلي","المشرف","دور المشرف","الموقع الجغرافي","الغرض","الحالة"]:["Visit ID","Planned Date","Planned Time","Actual Start","Actual Completion","Supervisor","Supervisor Role","Geography","Purpose","Status"];
 return <div className="border rounded-lg overflow-x-auto" dir={isRtl?"rtl":"ltr"}><table className="w-full min-w-[980px] text-xs"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{headers.map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{visits.map(v=><tr key={v.id} className="border-t"><td className="p-3 font-mono">{v.id}</td><td className="p-3">{v.plannedDate||v.visitDate}</td><td className="p-3">{v.plannedTime||"—"}</td><td className="p-3">{v.startedAt||"—"}</td><td className="p-3">{v.completedAt||"—"}</td><td className="p-3">{supervisorIdentityPresentation(supervisors[v.supervisorId],lang)}</td><td className="p-3">{projectedRole(v.supervisorId)}</td><td className="p-3">{geography(v)}</td><td className="p-3">{supervisorPresentationLabel(v.purpose,lang)}</td><td className="p-3">{supervisorPresentationLabel(v.status,lang)}</td></tr>)}</tbody></table></div>;
}
