import { defaultOfferScopeDependencies } from "./offerAdministrationService";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { parsePharmacyOfferReadRequest, physicalDemandIsAvailable, resolveScopedPharmacyOffers as resolveScopedPharmacyOffersService } from "./pharmacyOfferReadService";
import type { CanonicalOfferDefinition } from "../src/features/offers/types";

const resolveScopedPharmacyOffers = (uid: string, request: any, dependencies: any = {}) => resolveScopedPharmacyOffersService(uid, request, { readTransactionMarket: async () => ({ status: "RESOLVED", market: { marketId: "SYNTH-MARKET", countryId: "C1", countryNameEn: "Synthetic Country", countryNameAr: "بلد", active: true, currencyCode: "TST", currencySymbol: "T", symbolPosition: "BEFORE", decimalPlaces: 2, numeralLocale: "en-US", timezone: "UTC", workingWeekdays: [1], normalWorkdayStart: "09:00", normalWorkdayEnd: "17:00", checkInOpensAt: "08:00", autoCheckoutAt: "18:00" } }), ...dependencies, offerScopeDependencies: defaultOfferScopeDependencies });
const scopeRepository = (role = "Sales Representative", areaId = "A1") => ({ hierarchy: { async getUser(uid: string) { if (uid === "A") return { id: "A", role: "Super Admin" }; return { managerId: "A", id: "REP", role, active: true, status: "Active", securityScope: "Territory Only", areaIds: [areaId] }; }, async getDirectReports() { return []; }, async getAllUsers() { return []; }, async getRolePermissions() { return null; } }, async getGeographyCatalog() { return { countries: [{ id: "C1", active: true }], districts: [{ id: "D1", countryId: "C1", active: true }], cities: [{ id: "CT1", countryId: "C1", districtId: "D1", active: true }], areas: [{ id: areaId, countryId: "C1", districtId: "D1", cityId: "CT1", active: true }], nodes: [{ countryId: "C1", regionId: "D1", districtId: "D1", cityId: "CT1", areaId, active: true }] }; }, async getTerritoryAssignments() { return [{ assignmentId: "TA", userId: "REP", countryId: "C1", districtId: "D1", cityId: "CT1", areaId, status: "Active", active: true }]; }, async getProductAssignments() { return [{ assignmentId: "PA", userId: "REP", productId: "P1", status: "Active", active: true, effectiveFrom: "2020-01-01", effectiveTo: "2035-01-01", assignedAt: "2020-01-01", assignedBy: "TEST" }]; }, async getProducts() { return [{ id: "P1", name: "P1", brand: "P1", sku: "P1", therapeuticArea: "T", price: 1, stock: 1, isActive: true }]; } }) as any;
const offer = (overrides: Record<string, unknown> = {}): CanonicalOfferDefinition => ({ id: "O1", schemaVersion: 1, offerVersion: 1, revision: 1, code: "O1", name: "Ten percent", type: "PRODUCT_PERCENTAGE", lifecycleStatus: "ACTIVE", productScope: { mode: "SELECTED_PRODUCTS", productIds: ["P1"] }, benefit: { kind: "PRODUCT_PERCENTAGE", percentage: 10, base: "ELIGIBLE_PAID_PRODUCT_LINES" }, eligibility: { audienceType: "ALL_SALES_REPRESENTATIVES", startAt: "2026-01-01T00:00:00.000Z", endAt: "2026-12-31T23:59:59.000Z" }, stackingPolicy: { mode: "NO_STACKING", priority: 1, maximumProductOrQuantityOffersPerPaidLine: 1, maximumInvoicePercentageOffersPerInvoice: 1 }, createdAt: "2026-01-01T00:00:00.000Z", createdBy: "A", updatedAt: "2026-01-01T00:00:00.000Z", updatedBy: "A", ...overrides } as CanonicalOfferDefinition);
const buyOffer = (): CanonicalOfferDefinition => offer({ type: "BUY_X_GET_Y", benefit: { kind: "BUY_X_GET_Y", buyQuantity: 5, freeQuantity: 1, reward: { mode: "SAME_AS_TRIGGER" }, aggregationMode: "PER_PRODUCT", multiples: "REPEAT_COMPLETE_MULTIPLES", remainder: "NO_REWARD_BELOW_THRESHOLD" } });
const repository = (documents = [offer()], overrides: Record<string, unknown> = {}) => ({ async getUser(uid: string) { if (uid === "A") return { id: "A", role: "Super Admin" }; return { managerId: "A", id: "REP", role: "Sales Representative", active: true, companyId: "CO1", marketIds: ["M1"] }; }, async getPermissions() { return null; }, async getPharmacy() { return { active: true, companyId: "CO1", countryId: "C1", marketId: "M1", districtId: "D1", cityId: "CT1", areaId: "A1", type: "Retail" }; }, async getProduct() { return { price: 1, active: true, productType: "Commercial" }; }, async queryActive() { return documents.map(item => ({ id: item.id, data: item as any })); }, ...overrides }) as any;
const request = { pharmacyId: "PH1", productIds: ["P1"] };
const now = () => new Date("2026-06-01T00:00:00.000Z");

beforeEach(() => { vi.spyOn(defaultOfferScopeDependencies, "resolveScope").mockImplementation(async uid => ({ actorUid: uid, authorized: true, productIds: ["P1"], productGroupIds: [], queryPlan: { denyAll: false } } as any)); vi.stubEnv("OFFER_RUNTIME_MAX_ACTIVE_DOCUMENTS", "250"); vi.stubEnv("OFFER_RUNTIME_MAX_AUDIENCE_LOOKUPS", "3000"); });
afterEach(() => vi.unstubAllEnvs());

describe("canonical Pharmacy Visit Offer read", () => {
  it("accepts only bounded request context and rejects a client clock", () => { expect(parsePharmacyOfferReadRequest(request)).toEqual(request); expect(parsePharmacyOfferReadRequest({ ...request, companyId: "CO1" })).toBeNull(); expect(parsePharmacyOfferReadRequest({ ...request, at: "2026-06-01T00:00:00.000Z" })).toBeNull(); });
  it("returns an active canonical scoped Offer", async () => { const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository(), now }); expect(result.authorized).toBe(true); expect(result.offers.map(item => item.id)).toEqual(["O1"]); });
  it.each(["SCHEDULED", "PAUSED", "EXPIRED", "CANCELLED", "DRAFT", "PENDING_APPROVAL"])("excludes %s", async status => { const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([offer({ lifecycleStatus: status })]), now }); expect(result.offers).toEqual([]); });
  it("uses only the injected authoritative clock for current, future and expired Offers", async () => { const future = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository(), now: () => new Date("2025-12-31T23:59:59.000Z") }); const expired = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository(), now: () => new Date("2027-01-01T00:00:00.000Z") }); expect(future.offers).toEqual([]); expect(expired.offers).toEqual([]); });
  it("advises that a complete quantity reward is unavailable without exposing stock", async () => { const reward = buyOffer(); const result = await resolveScopedPharmacyOffers("REP", { ...request, paidLines: [{ lineId: "L1", productId: "P1", quantity: 5 }] }, { operationalScopeRepository: scopeRepository(), repository: repository([reward], { async getProduct() { return { price: 1, active: true, productType: "Commercial", stockQuantity: 0 }; } }), now }); expect(result.offers).toEqual([]); expect(result.unavailableOfferIds).toEqual([reward.id]); expect(result).not.toHaveProperty("stockQuantity"); });
  it("requires paid plus free physical stock during initial readiness", async () => { const reward = buyOffer(); const query = { ...request, paidLines: [{ lineId: "L1", productId: "P1", quantity: 10 }] }; const atTen = await resolveScopedPharmacyOffers("REP", query, { operationalScopeRepository: scopeRepository(), repository: repository([reward], { async getProduct() { return { price: 1, active: true, productType: "Commercial", stockQuantity: 10 }; } }), now }); const atTwelve = await resolveScopedPharmacyOffers("REP", query, { operationalScopeRepository: scopeRepository(), repository: repository([reward], { async getProduct() { return { price: 1, active: true, productType: "Commercial", stockQuantity: 12 }; } }), now }); expect(atTen.unavailableOfferIds).toEqual([reward.id]); expect(atTwelve.offers.map(item => item.id)).toEqual([reward.id]); });
  it("aggregates duplicate paid lines and multiple rewards for one product", () => { const products = new Map([["P1", { stockQuantity: 14 }]]); expect(physicalDemandIsAvailable([{ productId: "P1", quantity: 5 }, { productId: "P1", quantity: 5 }], [{ rewardProductId: "P1", quantity: 2 }, { rewardProductId: "P1", quantity: 2 }], products)).toBe(true); expect(physicalDemandIsAvailable([{ productId: "P1", quantity: 5 }, { productId: "P1", quantity: 5 }], [{ rewardProductId: "P1", quantity: 2 }, { rewardProductId: "P1", quantity: 3 }], products)).toBe(false); });
  it("counts selected-product rewards separately from paid demand", () => { const products = new Map([["P1", { stockQuantity: 10 }], ["R", { stockQuantity: 2 }]]); expect(physicalDemandIsAvailable([{ productId: "P1", quantity: 10 }], [{ rewardProductId: "R", quantity: 2 }], products)).toBe(true); expect(physicalDemandIsAvailable([{ productId: "P1", quantity: 10 }], [{ rewardProductId: "R", quantity: 3 }], products)).toBe(false); });
  it("allows one selected reward that fits but rejects the combined selection", () => { const products = new Map([["P1", { stockQuantity: 13 }]]); const paid = [{ productId: "P1", quantity: 10 }]; expect(physicalDemandIsAvailable(paid, [{ rewardProductId: "P1", quantity: 2 }], products)).toBe(true); expect(physicalDemandIsAvailable(paid, [{ rewardProductId: "P1", quantity: 2 }, { rewardProductId: "P1", quantity: 2 }], products)).toBe(false); });
  it("keeps discount-only Offers independent of reward stock", async () => { const result = await resolveScopedPharmacyOffers("REP", { ...request, paidLines: [{ lineId: "L1", productId: "P1", quantity: 10 }] }, { operationalScopeRepository: scopeRepository(), repository: repository([offer()], { async getProduct() { return { price: 1, active: true, productType: "Commercial", stockQuantity: 0 }; } }), now }); expect(result.offers.map(item => item.id)).toEqual(["O1"]); });
  it("fails closed for legacy and malformed records", async () => { const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([{ id: "OLD", type: "FIXED_DISCOUNT" } as any, offer({ id: "BAD", schemaVersion: 99 })]), now }); expect(result.offers).toEqual([]); });
  it("denies missing capability and wrong territory", async () => { const denied = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([], { async getPermissions() { return { offerCapabilities: { "offers.applyDuringVisit": false } }; } }) }); expect(denied.code).toBe("OFFER_PERMISSION_DENIED"); const area = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository("Sales Representative", "A2"), repository: repository() }); expect(area.code).toBe("OFFER_SCOPE_DENIED"); });
  it("rejects inactive/deleted products and inactive pharmacies", async () => { const product = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([], { async getProduct() { return null; } }) }); expect(product.code).toBe("OFFER_PRODUCT_NOT_FOUND"); const pharmacy = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([], { async getPharmacy() { return { active: false }; } }) }); expect(pharmacy.code).toBe("OFFER_PHARMACY_INACTIVE"); });
});

// Step 6 capacities are independent of selection limits and administrative pagination.
describe("Step 6 complete discovery", () => {
  it.each([0, 25, 249, 250])("evaluates all %i documents, including the final applicable Offer", async count => {
    const docs = Array.from({ length: count }, (_, i) => offer({ id: `O${String(i).padStart(3, "0")}` }));
    const result = await resolveScopedPharmacyOffers("REP", request, { repository: repository(docs), operationalScopeRepository: scopeRepository(), now });
    expect(result.complete).toBe(true);
    expect(result.offers).toHaveLength(count);
    if (count) expect(result.offers.at(-1)?.id).toBe(docs.at(-1)?.id);
  });
  it("fails at 251 without evaluating any returned definition or returning partial fields", async () => {
    const data = { get schemaVersion() { throw new Error("must not evaluate"); } };
    const repo = repository([], { queryActive: vi.fn(async () => Array.from({ length: 251 }, (_, i) => ({ id: `O${i}`, data }))) });
    await expect(resolveScopedPharmacyOffers("REP", request, { repository: repo, operationalScopeRepository: scopeRepository(), now })).rejects.toMatchObject({ code: "OFFER_DISCOVERY_CAPACITY_EXCEEDED", status: 503, complete: false });
    expect(repo.queryActive).toHaveBeenCalledWith(251);
  });
  it("fails configuration before reads", async () => {
    vi.stubEnv("OFFER_RUNTIME_MAX_ACTIVE_DOCUMENTS", "");
    const repo = repository([], { getUser: vi.fn() });
    await expect(resolveScopedPharmacyOffers("REP", request, { repository: repo })).rejects.toMatchObject({ code: "OFFER_CONFIGURATION_UNAVAILABLE", complete: false });
    expect(repo.getUser).not.toHaveBeenCalled();
  });
});

describe("obsolete commercial membership never authorizes pharmacy access", () => {
  it.each([{}, { companyIds: ["UNRELATED"], marketIds: ["OTHER-MARKET"] }])("allows canonical pharmacy access independently of old membership %j", async legacy => {
    const getUser = async (id: string) => id === "A" ? { id, role: "Super Admin" } : { id, role: "Sales Representative", active: true, managerId: "A", ...legacy };
    const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([offer()], { getUser }), now });
    expect(result.authorized).toBe(true); expect(result.offers).toHaveLength(1);
  });
  it("matching commercial fields cannot grant unauthorized geography", async () => {
    const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository("Sales Representative", "OTHER-AREA"), repository: repository(), now });
    expect(result.authorized).toBe(false); expect(result.offers).toEqual([]);
  });
  it.each(["ALL_PRODUCTS", "SELECTED_PRODUCTS"])("creator scope loss makes %s inapplicable without mutating definitions", async mode => {
    const definition = offer({ productScope: { mode, productIds: mode === "ALL_PRODUCTS" ? [] : ["P1"] }, updatedBy: "OTHER", makerIds: ["OTHER"] });
    const before = structuredClone(definition);
    vi.spyOn(defaultOfferScopeDependencies, "resolveScope").mockImplementation(async uid => ({ actorUid: uid, authorized: true, productIds: ["P2"], productGroupIds: [], queryPlan: { denyAll: false } } as any));
    const result = await resolveScopedPharmacyOffers("REP", request, { operationalScopeRepository: scopeRepository(), repository: repository([definition]), now });
    expect(result.offers).toEqual([]); expect(definition).toEqual(before);
  });
});
