import fs from "node:fs";
import { describe, expect, it, vi } from "vitest";
import type { OrderRecord, Pharmacy } from "../src/types";
import type { OperationalScopeRepository } from "./operationalScopeRepository";
import type { EffectiveOperationalScope } from "./operationalScopeService";
import { filterPharmacyOrdersWithinOperationalScope, parsePharmacyOrderReadRequest, projectPharmacyOrderSummary, resolveScopedPharmacyOrderRead, type PharmacyOrderReadRepository } from "./pharmacyOrderReadService";

const order = (id: string, uid = "ACTOR", pharmacyId = "PH1", areaId: string | undefined = "A1", date = "2026-08-01"): OrderRecord & Record<string, unknown> => ({ id, displayNumber: `ORD-${id}`, pharmacyId, pharmacyName: pharmacyId, createdByUid: uid, salesRepUid: uid, createdBy: "Display Name", salesRep: "Display Name", areaId, countryId: "C1", status: "PENDING_FINANCE_REVIEW", date, createdAt: `${date}T10:00:00Z`, total: 20, subtotal: 25, discount: 5, netTotal: 20, paidStatus: "Unpaid", paidAmount: 0, items: [{ id: "P1", name: "Product", quantity: 2, price: 10, total: 20 }], receiptImage: "SECRET", paymentEvidence: "SECRET", chequeNumber: "SECRET", financeNotes: "SECRET", operationsRemarks: "SECRET", deliveryOfficerPhone: "SECRET", inventoryDetails: "SECRET", history: [{ secret: true }] });
const pharmacy = (id = "PH1", areaId = "A1"): Pharmacy => ({ id, name: id, territory: areaId, region: "R1", address: "Street", outstandingBalance: 0, areaId, active: true, status: "Active" });
const request = { pharmacyId: "PH1", fromDate: "2026-06-01", toDate: "2026-08-11", pageSize: 50 };
const scope = (overrides: Partial<EffectiveOperationalScope> = {}): EffectiveOperationalScope => ({ authorized: true, actorUid: "ACTOR", role: "Sales Representative", boundaryKind: "AREA", subjectMode: "SELF", subjectUids: ["ACTOR"], countryIds: ["C1"], regionIds: ["R1"], districtIds: ["R1"], cityIds: ["CT1"], areaIds: ["A1"], productIds: ["P1"], productGroupIds: [], queryPlan: { denyAll: false, areaIdChunks: [["A1"]], subjectUidChunks: [["ACTOR"]], productIdChunks: [["P1"]], requiresPostFilter: true }, diagnostics: { excludedAssignmentIds: [], malformedAssignmentIds: [], outsideBoundaryAssignmentIds: [] }, ...overrides });
function operationalRepository({ role = "Sales Representative", manager = false, actorActive = true, configuredAreas = ["A1"], assignmentAreas = ["A1"] } = {}): OperationalScopeRepository {
  const actor = { id: "ACTOR", email: "actor@test", role, active: actorActive, loginAllowed: true, status: "Active", securityScope: "Area", areaIds: configuredAreas, country: "C1" };
  const rep = { id: "REP1", email: "rep@test", role: "Sales Representative", active: true, managerId: "ACTOR" };
  return { hierarchy: { async getUser(uid) { return uid === "ACTOR" ? actor : uid === "REP1" ? rep : null; }, async getDirectReports(uid) { return manager && uid === "ACTOR" ? [rep] : []; }, async getAllUsers() { return manager ? [actor, rep] : [actor]; }, async getRolePermissions() { return null; } }, async getGeographyCatalog() { return { countries: [{ id: "C1", active: true }], districts: [{ id: "R1", countryId: "C1", active: true }], cities: [{ id: "CT1", districtId: "R1", countryId: "C1", active: true }, { id: "CT2", districtId: "R1", countryId: "C1", active: true }], areas: [{ id: "A1", cityId: "CT1", districtId: "R1", countryId: "C1", active: true }, { id: "A2", cityId: "CT2", districtId: "R1", countryId: "C1", active: true }], nodes: [{ areaId: "A1", cityId: "CT1", districtId: "R1", regionId: "R1", countryId: "C1", active: true }, { areaId: "A2", cityId: "CT2", districtId: "R1", regionId: "R1", countryId: "C1", active: true }] }; }, async getTerritoryAssignments(subjects) { return assignmentAreas.map((areaId, i) => ({ assignmentId: `TA${i}`, userId: manager ? "REP1" : subjects[0], status: "Active", active: true, countryId: "C1", regionId: "R1", districtId: "R1", cityId: areaId === "A1" ? "CT1" : "CT2", areaId })); }, async getProductAssignments() { return [{ assignmentId: "PA1", userId: manager ? "REP1" : "ACTOR", productId: "P1", effectiveFrom: "2026-01-01", effectiveTo: "2030-01-01", assignedAt: "2026-01-01", assignedBy: "TEST", status: "Active", active: true }]; }, async getProducts() { return [{ id: "P1", name: "P1", brand: "P1", sku: "P1", therapeuticArea: "TA", price: 1, stock: 1, isActive: true }]; } };
}
const orderRepo = (records: OrderRecord[]): PharmacyOrderReadRepository => ({ queryByCanonicalSubjectUids: vi.fn(async () => records) });
const pharmacyRepo = (records = [pharmacy()]) => ({ queryByAreaIds: vi.fn(async () => records) });

describe("WP5.2F.6A canonical pharmacy order summary/history READ", () => {
  it("1. Sales Rep sees own canonical order", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1")], scope(), new Set(["PH1"]), request).summaries.map(o => o.id)).toEqual(["1"]));
  it("2. Sales Rep cannot see another rep order", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1", "OTHER")], scope(), new Set(["PH1"]), request).summaries).toEqual([]));
  it("3. same-area pharmacy visibility alone does not grant another rep order", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1", "OTHER", "PH1", "A1")], scope(), new Set(["PH1"]), request).summaries).toEqual([]));
  it("4. Supervisor sees authorized subordinate order", async () => { const result = await resolveScopedPharmacyOrderRead("ACTOR", request, { operationalScopeRepository: operationalRepository({ role: "Sales Supervisor", manager: true }), orderReadRepository: orderRepo([order("1", "REP1")]), pharmacyReadRepository: pharmacyRepo() }); expect(result.orders.map(o => o.id)).toEqual(["1"]); });
  it("5. non-subordinate order excluded", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1", "OTHER")], scope({ role: "Sales Supervisor", subjectMode: "HIERARCHY", subjectUids: ["ACTOR", "REP1"] }), new Set(["PH1"]), request).summaries).toEqual([]));
  for (const [number, role] of [[6, "Area Sales Manager"], [7, "Sales Manager"], [8, "Sales & Marketing Manager"], [9, "Country Manager"], [10, "General Manager"], [11, "Super Admin"]] as const) it(`${number}. ${role} remains explicitly bounded`, () => { const manager = scope({ role, subjectMode: "HIERARCHY", subjectUids: ["ACTOR", "REP1"] }); expect(filterPharmacyOrdersWithinOperationalScope([order("IN", "REP1"), order("SUB", "OTHER"), order("AREA", "REP1", "PH1", "A2")], manager, new Set(["PH1"]), request).summaries.map(o => o.id)).toEqual(["IN"]); });
  for (const [number, role] of [[12, "Finance Manager"], [13, "Finance Officer"], [14, "Treasury Officer"], [15, "Warehouse Manager"], [16, "Inventory Officer"], [17, "Store Manager"], [18, "Delivery Officer"], [19, "Order Operations Officer"], [20, "Product Manager"], [21, "Medical Manager"]] as const) it(`${number}. ${role} summary access fails closed`, async () => { const query = vi.fn(); const result = await resolveScopedPharmacyOrderRead("ACTOR", request, { operationalScopeRepository: operationalRepository({ role }), orderReadRepository: { queryByCanonicalSubjectUids: query }, pharmacyReadRepository: pharmacyRepo() }); expect(result.authorized).toBe(false); expect(query).not.toHaveBeenCalled(); });
  it("22. inactive actor denied before order query", async () => { const query = vi.fn(); const result = await resolveScopedPharmacyOrderRead("ACTOR", request, { operationalScopeRepository: operationalRepository({ actorActive: false }), orderReadRepository: { queryByCanonicalSubjectUids: query }, pharmacyReadRepository: pharmacyRepo() }); expect(result.code).toBe("ACTOR_INACTIVE"); expect(query).not.toHaveBeenCalled(); });
  it("23. denyAll denies every order", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1")], scope({ queryPlan: { ...scope().queryPlan, denyAll: true } }), new Set(["PH1"]), request).summaries).toEqual([]));
  it("24. modern canonical pharmacy is allowed", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1")], scope(), new Set(["PH1"]), request).summaries).toHaveLength(1));
  it("25. outside-bound pharmacy excluded", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1", "ACTOR", "OUT")], scope(), new Set(["PH1"]), { ...request, pharmacyId: undefined }).summaries).toEqual([]));
  it("26. modern canonical area allowed", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1")], scope(), new Set(["PH1"]), request).summaries).toHaveLength(1));
  it("27. outside-bound area excluded", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1", "ACTOR", "PH1", "A2")], scope(), new Set(["PH1"]), request).summaries).toEqual([]));
  it("28. canonical multi-area assignments are not narrowed by legacy profile geography", async () => { const result = await resolveScopedPharmacyOrderRead("ACTOR", request, { operationalScopeRepository: operationalRepository({ configuredAreas: ["A1"], assignmentAreas: ["A1", "A2"] }), orderReadRepository: orderRepo([order("A1"), order("A2", "ACTOR", "PH1", "A2")]), pharmacyReadRepository: pharmacyRepo() }); expect(result.orders.map(o => o.id)).toEqual(["A1", "A2"]); });
  it("29. safe legacy missing-area order uses bounded pharmacy resolution", async () => { const legacy = order("1"); delete legacy.areaId; const bounded = pharmacyRepo(); const result = await resolveScopedPharmacyOrderRead("ACTOR", request, { operationalScopeRepository: operationalRepository(), orderReadRepository: orderRepo([legacy]), pharmacyReadRepository: bounded }); expect(result.orders.map(o => o.id)).toEqual(["1"]); expect(bounded.queryByAreaIds).toHaveBeenCalledWith(["A1"]); });
  it("30. legacy pharmacy outside bounded set denied", () => { const legacy = order("1", "ACTOR", "OUT"); delete legacy.areaId; expect(filterPharmacyOrdersWithinOperationalScope([legacy], scope(), new Set(["PH1"]), { ...request, pharmacyId: undefined }).summaries).toEqual([]); });
  it("31. ambiguous legacy identity fails closed", () => { const legacy = order("1"); delete legacy.createdByUid; delete legacy.salesRepUid; const result = filterPharmacyOrdersWithinOperationalScope([legacy], scope(), new Set(["PH1"]), request); expect(result.summaries).toEqual([]); expect(result.excludedLegacyOrderIds).toEqual(["1"]); });
  it("32. backend contains no whole orders collection scan", () => { const source = fs.readFileSync(new URL("./pharmacyOrderReadService.ts", import.meta.url), "utf8"); expect(source).toContain('.where("createdByUid", "in", subjects)'); expect(source).toContain('.where("salesRepUid", "in", subjects)'); expect(source).not.toMatch(/collection\("orders"\)\s*\.get\s*\(/); });
  it("33. summary excludes receipt and payment evidence", () => { const summary = projectPharmacyOrderSummary(order("1"), "2026-08-01") as unknown as Record<string, unknown>; expect(summary.receiptImage).toBeUndefined(); expect(summary.paymentEvidence).toBeUndefined(); });
  it("34. summary excludes cheque information", () => expect((projectPharmacyOrderSummary(order("1"), "2026-08-01") as unknown as Record<string, unknown>).chequeNumber).toBeUndefined());
  it("35. summary excludes Finance and Ops remarks", () => { const summary = projectPharmacyOrderSummary(order("1"), "2026-08-01") as unknown as Record<string, unknown>; expect(summary.financeNotes).toBeUndefined(); expect(summary.operationsRemarks).toBeUndefined(); });
  it("36. summary excludes delivery PII", () => expect((projectPharmacyOrderSummary(order("1"), "2026-08-01") as unknown as Record<string, unknown>).deliveryOfficerPhone).toBeUndefined());
  it("37. summary excludes inventory and stock internals", () => expect((projectPharmacyOrderSummary(order("1"), "2026-08-01") as unknown as Record<string, unknown>).inventoryDetails).toBeUndefined());
  it("38. date range bounded", () => { expect(parsePharmacyOrderReadRequest({ fromDate: "2026-01-01", toDate: "2026-08-01" })).toBeNull(); expect(parsePharmacyOrderReadRequest({ fromDate: "2026-06-01", toDate: "2026-08-01" })).not.toBeNull(); });
  it("39. page size bounded", () => { expect(parsePharmacyOrderReadRequest({ pageSize: 101 })).toBeNull(); expect(parsePharmacyOrderReadRequest({ pageSize: 100 })).not.toBeNull(); });
  it("40. cursor context is bound", async () => { const base = { ...request, pageSize: 1 }; const deps = { operationalScopeRepository: operationalRepository(), orderReadRepository: orderRepo([order("A"), order("B")]), pharmacyReadRepository: pharmacyRepo() }; const first = await resolveScopedPharmacyOrderRead("ACTOR", base, deps); expect(first.nextCursor).toBeTruthy(); const replay = await resolveScopedPharmacyOrderRead("ACTOR", { ...base, pharmacyId: "PH2", cursor: first.nextCursor }, deps); expect(replay.code).toBe("INVALID_ORDER_CURSOR"); });
  it("41. deterministic ordering", () => expect(filterPharmacyOrdersWithinOperationalScope([order("Z"), order("B", "ACTOR", "PH1", "A1", "2026-08-02"), order("A")], scope(), new Set(["PH1"]), request).summaries.map(o => o.id)).toEqual(["B", "A", "Z"]));
  it("42. duplicates deduplicate", () => expect(filterPharmacyOrdersWithinOperationalScope([order("1"), order("1")], scope(), new Set(["PH1"]), request).summaries).toHaveLength(1));
  it("43. malformed records excluded safely", () => expect(filterPharmacyOrdersWithinOperationalScope([{ ...order("1"), pharmacyId: "" }], scope(), new Set(["PH1"]), request).summaries).toEqual([]));
  it("45. endpoint requires Firebase authentication", () => expect(fs.readFileSync(new URL("../server.ts", import.meta.url), "utf8")).toContain('app.post("/api/pharmacy-orders/scoped-query", requireFirebaseAuth'));
});
