import { describe, expect, it } from "vitest";
import fs from "node:fs";
import { authorizeSampleApprovalDecision, parseSampleApprovalDecisionRequest, SampleApprovalError } from "./sampleApprovalService";
import { Role, type Permissions, type SampleRequest, type User } from "../src/types";

const actor = (overrides: Partial<User> = {}): User => ({ id: "MSPR", name: "Medical Supervisor", email: "supervisor@example.test", role: Role.MEDICAL_SUPERVISOR, active: true, loginAllowed: true, ...overrides } as User);
const request = (overrides: Partial<SampleRequest> = {}): SampleRequest => ({ id: "REQ-MEDTEST", requesterId: "medtest", repId: "medtest", sampleSkuId: "SKU-1", productId: "PROD-1", quantityRequested: 50, reason: "Field need", requestedForPhysicianId: "PHY-267", source: "STANDALONE", urgent: false, status: "PENDING_APPROVAL", createdAt: "2026-08-25T00:00:00Z", createdBy: "medtest", ...overrides });
const permissions = (approve = true): Permissions => ({ active: true, sampleCapabilities: { APPROVE_SAMPLE_REQUEST: approve, REJECT_SAMPLE_REQUEST: approve } } as unknown as Permissions);
const decide = (overrides: Record<string, unknown> = {}) => authorizeSampleApprovalDecision({ actor: actor(), permissions: permissions(), descendantUids: ["medtest"], request: request(), decision: { requestId: "REQ-MEDTEST", decision: "APPROVED", approvedQuantity: 5 }, occurredAt: "2026-08-25T01:00:00Z", ...overrides });
const code = (fn: () => unknown) => { try { fn(); return "PASS"; } catch (error) { return (error as SampleApprovalError).code; } };

describe("authoritative Samples approval decision", () => {
  it("authorizes Medical Supervisor direct active descendant and existing partial approval", () => { const result = decide(); expect(result.approval.approvedQuantity).toBe(5); expect(result.request.status).toBe("AWAITING_ALLOCATION"); });
  it("authorizes Medical Manager descendant when its existing capability permits", () => expect(decide({ actor: actor({ id: "MMGR", role: Role.MEDICAL_MANAGER }), descendantUids: ["MSPR", "medtest"] }).approval.approverId).toBe("MMGR"));
  it("applies existing Admin governance through capability and canonical descendants", () => expect(decide({ actor: actor({ id: "ADMIN", role: Role.ADMIN }), descendantUids: ["medtest"] }).approval.approverId).toBe("ADMIN"));
  it("denies unrelated supervisor", () => expect(code(() => decide({ descendantUids: ["another-rep"] })) ).toBe("SAMPLE_REQUEST_DESCENDANT_DENIED"));
  it("denies inactive or login-disabled supervisor", () => { expect(code(() => decide({ actor: actor({ active: false }) }))).toBe("SAMPLE_APPROVAL_ACTOR_INACTIVE"); expect(code(() => decide({ actor: actor({ loginAllowed: false }) }))).toBe("SAMPLE_APPROVAL_ACTOR_INACTIVE"); });
  it("denies actor without APPROVE_SAMPLE_REQUEST", () => expect(code(() => decide({ permissions: permissions(false) }))).toBe("SAMPLE_APPROVAL_CAPABILITY_DENIED"));
  it("denies self approval", () => expect(code(() => decide({ actor: actor({ id: "medtest" }) }))).toBe("SELF_APPROVAL_PROHIBITED"));
  it("denies already approved, rejected, and duplicate approval", () => { expect(code(() => decide({ request: request({ status: "AWAITING_ALLOCATION" }) }))).toBe("REQUEST_NOT_PENDING"); expect(code(() => decide({ request: request({ status: "REJECTED" }) }))).toBe("REQUEST_NOT_PENDING"); expect(code(() => decide({ approvalAlreadyExists: true }))).toBe("REQUEST_NOT_PENDING"); });
  it("denies forged request ownership and ignores forged repId because parser rejects it", () => { expect(code(() => decide({ request: request({ requesterId: "OTHER" }) }))).toBe("SAMPLE_REQUEST_OWNERSHIP_INVALID"); expect(parseSampleApprovalDecisionRequest({ requestId: "REQ", decision: "APPROVED", approvedQuantity: 2, repId: "FORGED" })).toBeNull(); });
  it("validates quantities without disguising authorization errors", () => { expect(decide({ decision: { requestId: "REQ-MEDTEST", decision: "APPROVED", approvedQuantity: 2 } }).approval.approvedQuantity).toBe(2); expect(code(() => decide({ decision: { requestId: "REQ-MEDTEST", decision: "APPROVED", approvedQuantity: 51 } }))).toBe("APPROVED_QUANTITY_EXCEEDED"); });
  it("persists canonical identities and never creates allocation", () => { const result = decide(); expect(result.approval.approverId).toBe("MSPR"); expect(result.request.requestedForPhysicianId).toBe("PHY-267"); expect(result).not.toHaveProperty("allocation"); });
  it("uses one Admin SDK transaction for approval, request and audit, with create-once retry protection", () => { const source = fs.readFileSync(new URL("./sampleApprovalService.ts", import.meta.url), "utf8"); expect(source).toContain("db.runTransaction"); expect(source).toContain("tx.create(approvalRef"); expect(source).toContain("tx.update(requestRef"); expect(source).toContain("tx.create(auditRef"); expect(source).toContain("existingApproval.exists"); });
  it("removes the direct browser write bypass and protects the endpoint", () => { const component = fs.readFileSync(new URL("../src/components/samples/SampleApprovals.tsx", import.meta.url), "utf8"); const client = fs.readFileSync(new URL("../src/lib/sampleApprovalClient.ts", import.meta.url), "utf8"); const server = fs.readFileSync(new URL("../server.ts", import.meta.url), "utf8"); expect(component).not.toContain("persistSampleRequestDecision"); expect(component).not.toContain("writeBatch"); expect(client).toContain('/api/samples/approval-decision'); expect(server).toContain('app.post("/api/samples/approval-decision", requireFirebaseAuth'); });
  it("displays canonical user and physician names while retaining IDs", () => { const component = fs.readFileSync(new URL("../src/components/samples/SampleApprovals.tsx", import.meta.url), "utf8"); expect(component).toContain("physicians.find(physician => physician.id === request.requestedForPhysicianId)?.name"); expect(component).toContain("users.find(user => user.id === request.updatedBy)?.name"); });
});
