import { describe, expect, it } from "vitest";
import { addCalendarDays, aggregateSampleRequests, assertRollingPhysicianLimit, distributedQuantityWithinRollingWindow, marketLocalDate, planRepresentativeFefo, rollingWindowStart } from "./sampleDistributionPolicy";

const sku = (overrides: Record<string, unknown> = {}) => ({ id: "SKU-ALPHA", productId: "PRODUCT-ALPHA", name: "Sample Alpha", skuCode: "SKU-A", active: true, status: "ACTIVE", createdAt: "2026-01-01", createdBy: "fixture", ...overrides } as any);
const allocation = (id: string, batchId: string | undefined, remaining = 5, allocatedAt = "2026-01-01T00:00:00Z", overrides: Record<string, unknown> = {}) => ({ id, sampleSkuId: "SKU-ALPHA", productId: "PRODUCT-ALPHA", repId: "REP-ARBITRARY", quantityAllocated: remaining, quantityDistributed: 0, quantityRemaining: remaining, batchId, allocatedAt, allocatedBy: "fixture", status: "ACTIVE", reportingMonth: "2026-01", createdAt: allocatedAt, createdBy: "fixture", ...overrides } as any);
const batch = (id: string, expiryDate: string, overrides: Record<string, unknown> = {}) => ({ id, sampleSkuId: "SKU-ALPHA", batchNumber: `LOT-${id}`, expiryDate, receivedQuantity: 10, availableQuantity: 10, status: "AVAILABLE", receivedAt: "2026-01-01", receivedBy: "fixture", createdAt: "2026-01-01", createdBy: "fixture", ...overrides } as any);

describe("canonical sample distribution policy", () => {
  it("accepts quantities one and three per explicitly selected SKU", () => {
    expect(aggregateSampleRequests([{ productId: "P", sampleSkuId: "S1", productName: "", brand: "", quantity: 1 }])[0].quantity).toBe(1);
    expect(aggregateSampleRequests([{ productId: "P", sampleSkuId: "S1", productName: "", brand: "", quantity: 3 }])[0].quantity).toBe(3);
  });
  it("rejects quantity four", () => expect(() => aggregateSampleRequests([{ productId: "P", sampleSkuId: "S1", productName: "", brand: "", quantity: 4 }])).toThrow("SAMPLE_SKU_DISTRIBUTION_LIMIT_EXCEEDED"));
  it("aggregates duplicate SKU blocks before applying the cap", () => expect(() => aggregateSampleRequests([{ productId: "P", sampleSkuId: "S1", productName: "", brand: "", quantity: 2 }, { productId: "P", sampleSkuId: "S1", productName: "", brand: "", quantity: 2 }])).toThrow("SAMPLE_SKU_DISTRIBUTION_LIMIT_EXCEEDED"));
  it("keeps multiple explicit SKUs independent without a brand/SKU-count limit", () => expect(aggregateSampleRequests(["S1", "S2", "S3", "S4", "S5"].map(sampleSkuId => ({ productId: "P", sampleSkuId, productName: "", brand: "", quantity: 1 })))).toHaveLength(5));
  it("rejects missing explicit SKU identity", () => expect(() => aggregateSampleRequests([{ productId: "P", productName: "", brand: "", quantity: 1 }])).toThrow("INVALID_SAMPLE_REQUEST"));
  it("rejects one SKU presented under two products", () => expect(() => aggregateSampleRequests([{ productId: "P1", sampleSkuId: "S", productName: "", brand: "", quantity: 1 }, { productId: "P2", sampleSkuId: "S", productName: "", brand: "", quantity: 1 }])).toThrow("SAMPLE_SKU_PRODUCT_MISMATCH"));
  it("defines the inclusive rolling window as current local date minus 89 days", () => expect(rollingWindowStart("2026-08-19")).toBe("2026-05-22"));
  it("includes the exact 90-day boundary and excludes older records", () => expect(distributedQuantityWithinRollingWindow([{ physicianId: "D", quantity: 4, distributionDate: "2026-05-22", status: "DISTRIBUTED" }, { physicianId: "D", quantity: 7, distributionDate: "2026-05-21", status: "DISTRIBUTED" }], "D", "2026-08-19", "UTC")).toBe(4));
  it("excludes cancelled, rejected and non-distributed zero records", () => expect(distributedQuantityWithinRollingWindow([{ physicianId: "D", quantity: 4, distributionDate: "2026-08-01", status: "CANCELLED" }, { physicianId: "D", quantity: 4, distributionDate: "2026-08-01", status: "REJECTED" }, { physicianId: "D", quantity: 0, distributionDate: "2026-08-01" }], "D", "2026-08-19", "UTC")).toBe(0));
  it("allows A projected 40 and rejects 41", () => { const records = [{ physicianId: "D", quantity: 37, distributionDate: "2026-08-01", status: "DISTRIBUTED" }]; expect(assertRollingPhysicianLimit({ records, physicianId: "D", classification: "A", distributionDate: "2026-08-19", timezone: "UTC", proposedQuantity: 3 }).projected).toBe(40); expect(() => assertRollingPhysicianLimit({ records, physicianId: "D", classification: "A", distributionDate: "2026-08-19", timezone: "UTC", proposedQuantity: 4 })).toThrow("PHYSICIAN_ROLLING_SAMPLE_LIMIT_EXCEEDED"); });
  it("allows B projected 20 and rejects 21", () => { const records = [{ physicianId: "D", quantity: 17, distributionDate: "2026-08-01", status: "DISTRIBUTED" }]; expect(assertRollingPhysicianLimit({ records, physicianId: "D", classification: "B", distributionDate: "2026-08-19", timezone: "UTC", proposedQuantity: 3 }).projected).toBe(20); expect(() => assertRollingPhysicianLimit({ records, physicianId: "D", classification: "B", distributionDate: "2026-08-19", timezone: "UTC", proposedQuantity: 4 })).toThrow("PHYSICIAN_ROLLING_SAMPLE_LIMIT_EXCEEDED"); });
  it("fails closed for an unapproved classification", () => expect(() => assertRollingPhysicianLimit({ records: [], physicianId: "D", classification: "C", distributionDate: "2026-08-19", timezone: "UTC", proposedQuantity: 1 })).toThrow("SAMPLE_CLASSIFICATION_POLICY_REQUIRED"));
  it("uses the canonical market timezone for the distribution business date", () => expect(marketLocalDate("2026-08-18T23:30:00Z", "Asia/Tokyo")).toBe("2026-08-19"));
  it("accepts exactly 60 days remaining", () => expect(planRepresentativeFefo({ allocations: [allocation("A", "B")], batches: [batch("B", addCalendarDays("2026-08-19", 60))], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toHaveLength(1));
  it("rejects 59 days remaining and expired inventory", () => { expect(() => planRepresentativeFefo({ allocations: [allocation("A", "B")], batches: [batch("B", addCalendarDays("2026-08-19", 59))], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow("INSUFFICIENT_DISTRIBUTABLE_SAMPLE_STOCK"); expect(() => planRepresentativeFefo({ allocations: [allocation("A", "B")], batches: [batch("B", "2026-01-01")], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow(); });
  it("rejects malformed or impossible expiry dates", () => { for (const expiry of ["not-a-date", "2027-02-30"]) expect(() => planRepresentativeFefo({ allocations: [allocation("A", "B")], batches: [batch("B", expiry)], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow("INSUFFICIENT_DISTRIBUTABLE_SAMPLE_STOCK"); });
  it("rejects batchless allocation", () => expect(() => planRepresentativeFefo({ allocations: [allocation("A", undefined)], batches: [], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow("SAMPLE_ALLOCATION_BATCH_REQUIRED"));
  it("rejects another representative's allocation", () => expect(() => planRepresentativeFefo({ allocations: [allocation("A", "B", 5, "2026-01-01", { repId: "OTHER" })], batches: [batch("B", "2027-01-01")], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow("INSUFFICIENT_DISTRIBUTABLE_SAMPLE_STOCK"));
  it("rejects inactive SKU allocation relationship", () => expect(() => planRepresentativeFefo({ allocations: [allocation("A", "B", 5, "2026-01-01", { productId: "WRONG" })], batches: [batch("B", "2027-01-01")], repId: "REP-ARBITRARY", sku: sku(), quantity: 1, distributionDate: "2026-08-19" })).toThrow());
  it("uses deterministic FEFO then allocation time and preserves multi-batch lineage", () => { const plan = planRepresentativeFefo({ allocations: [allocation("LATE", "B2", 2, "2026-02-01"), allocation("EARLY", "B1", 2, "2026-01-01")], batches: [batch("B2", "2027-02-01"), batch("B1", "2027-01-01")], repId: "REP-ARBITRARY", sku: sku(), quantity: 3, distributionDate: "2026-08-19" }); expect(plan).toEqual([{ allocationId: "EARLY", batchId: "B1", batchNumber: "LOT-B1", expiryDate: "2027-01-01", quantity: 2 }, { allocationId: "LATE", batchId: "B2", batchNumber: "LOT-B2", expiryDate: "2027-02-01", quantity: 1 }]); });
});
