import { createHash, randomUUID } from "node:crypto";
import type { Transaction } from "firebase-admin/firestore";
import { Role, SUPERVISOR_VISIT_PURPOSES, type SupervisorCoachingAppraisal, type SupervisorCoachingFinalReviewDecision, type SupervisorCoachingPreRevisionSnapshot, type SupervisorCoachingReviewDecision, type SupervisorCoachingStatus, type SupervisorCoachingWorkflowPhase, type SupervisorIdentityPresentation, type SupervisorVisit, type SupervisorVisitCustomerType, type SupervisorVisitStatus } from "../src/types";
import { getFirebaseAdminServices } from "./firebaseAdmin";
import { createFirestoreOperationalScopeRepository, resolveOperationalScopeForActor, type OperationalScopeRepository } from "./operationalScopeRepository";
import { canonicalAreaIdForTerritoryAssignment } from "./operationalScopeService";
import { marketDateForInstant, marketTimeForInstant, validateMarketSettings, type MarketBusinessSettings } from "../src/lib/marketSettings";
import { filterPhysiciansWithinOperationalScope } from "./physicianReadService";
import { filterPharmaciesWithinOperationalScope } from "./pharmacyReadService";

const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const TIME = /^([01]\d|2[0-3]):[0-5]\d$/;
const validDate = (value:string) => DATE.test(value) && new Date(`${value}T12:00:00Z`).toISOString().slice(0,10) === value;
const validTimezone = (value:string) => { try { new Intl.DateTimeFormat("en-US", { timeZone: value }).format(); return Boolean(value); } catch { return false; } };
const hasCanonicalSchedule = (visit:SupervisorVisit) => validDate(text(visit.plannedDate)) && TIME.test(text(visit.plannedTime)) && validTimezone(text(visit.planningTimezone));
const PURPOSES = new Set<string>(SUPERVISOR_VISIT_PURPOSES);
const SUPERVISOR_ROLES = new Set<string>([Role.MEDICAL_SUPERVISOR, Role.SALES_SUPERVISOR]);
export type SupervisorVisitCreate = Pick<SupervisorVisit, "customerType" | "customerId" | "areaId" | "accompaniedRepresentativeId" | "purpose" | "objectives"> & { plannedDate: string; plannedTime: string; idempotencyKey: string };
export type SupervisorRepresentativeEligibilityRequest = Pick<SupervisorVisit, "customerType" | "customerId" | "areaId">;
export type SupervisorCustomerVisitHistoryRequest = Pick<SupervisorVisit, "customerType" | "customerId"> & { supervisorRole?: Role.MEDICAL_SUPERVISOR | Role.SALES_SUPERVISOR };
export type SupervisorVisitTransitionAction = "START" | "COMPLETE" | "CANCEL";
export interface SupervisorVisitTransition { visitId: string; action: SupervisorVisitTransitionAction; outcome: string; notes: string }
export interface SupervisorVisitReschedule { visitId: string; plannedDate: string; plannedTime: string }
export type AppraisalDraftFields = Pick<SupervisorCoachingAppraisal, "sections" | "sectionWeights" | "scores" | "comments" | "sectionNotes" | "strengths" | "improvementAreas" | "actionPlan" | "recommendations" | "overallRating">;
export type AppraisalEditableDraftFields = Omit<AppraisalDraftFields,"sectionWeights">;
export type AppraisalRevisionFields = Pick<SupervisorCoachingAppraisal, "scores" | "comments" | "sectionNotes" | "strengths" | "improvementAreas" | "actionPlan" | "recommendations" | "overallRating">;
export type AppraisalCreate = Pick<SupervisorCoachingAppraisal, "supervisorVisitId" | "appraisalType"> & AppraisalDraftFields;
export type AppraisalDraftSave = { appraisalId:string; expectedWorkflowVersion:number } & AppraisalEditableDraftFields;
export interface AppraisalSubmit { appraisalId:string; expectedWorkflowVersion:number }
export interface AppraisalRepresentativeReview { appraisalId:string; expectedWorkflowVersion:number; reviewDecision:SupervisorCoachingReviewDecision; representativeComment:string }
export interface AppraisalKeepUnchanged { appraisalId:string; expectedWorkflowVersion:number; supervisorRationale:string }
export interface AppraisalOpenRevision { appraisalId:string; expectedWorkflowVersion:number }
export type AppraisalRevisionSave = { appraisalId:string; expectedWorkflowVersion:number } & AppraisalRevisionFields;
export interface AppraisalFinalRepresentativeReview { appraisalId:string; expectedWorkflowVersion:number; reviewDecision:SupervisorCoachingFinalReviewDecision; representativeComment:string }
export interface AppraisalSignOff { appraisalId:string; expectedWorkflowVersion:number }

interface AppraisalMutationExpectation { status:SupervisorCoachingStatus; phase:SupervisorCoachingWorkflowPhase; workflowVersion:number; actorUid:string; actorKind:"SUPERVISOR"|"REPRESENTATIVE"; actorRole:string; areaIds:string[]; guard?:(current:SupervisorCoachingAppraisal)=>string|null; buildUpdates?:(current:SupervisorCoachingAppraisal)=>Partial<SupervisorCoachingAppraisal> }
interface AppraisalVoidExpectation { actorUid:string; actorRole:Role; occurredAt:string; auditId:string; appraisalId:string; expectedStatus:SupervisorCoachingStatus; expectedPhase:SupervisorCoachingWorkflowPhase; expectedWorkflowVersion:number; expectedRevisionNumber:0|1 }

export class SupervisorVisitError extends Error { constructor(public code: string, public status = 403) { super(code); } }
export interface SupervisorVisitRepository {
  getUser(id: string): Promise<any | null>;
  getCustomer(type: SupervisorVisitCustomerType, id: string): Promise<any | null>;
  getArea(id: string): Promise<any | null>;
  getMarkets(countryId: string): Promise<MarketBusinessSettings[]>;
  getTerritoryAssignments(userId: string): Promise<any[]>;
  getProductAssignments(userId: string): Promise<any[]>;
  createVisitIdempotently(visit: SupervisorVisit): Promise<{ visit: SupervisorVisit; replayed: boolean }>;
  listVisits(supervisorId: string): Promise<SupervisorVisit[]>;
  listCustomerVisits(customerType: SupervisorVisitCustomerType, customerId: string): Promise<SupervisorVisit[]>;
  getVisit(id: string): Promise<SupervisorVisit | null>;
  transitionVisit(id: string, expectedStatus: SupervisorVisitStatus, updates: Partial<SupervisorVisit>, voidTransition?:AppraisalVoidExpectation): Promise<SupervisorVisit | null>;
  rescheduleVisit(id: string, expectedStatus: "SCHEDULED", updates: Partial<SupervisorVisit>, audit:Record<string,unknown>): Promise<SupervisorVisit | null>;
  getAppraisal(id:string):Promise<SupervisorCoachingAppraisal|null>;
  linkAppraisal(visitId: string, appraisal: SupervisorCoachingAppraisal, audit:Record<string,unknown>): Promise<boolean>;
  updateAppraisal(id:string,expectation:AppraisalMutationExpectation,updates:Partial<SupervisorCoachingAppraisal>,audit:Record<string,unknown>):Promise<SupervisorCoachingAppraisal|null>;
  listSupervisorAppraisals(supervisorId: string): Promise<SupervisorCoachingAppraisal[]>;
  listRepresentativeAppraisals(representativeId: string): Promise<SupervisorCoachingAppraisal[]>;
}

export function createFirestoreSupervisorVisitRepository(): SupervisorVisitRepository {
  const db = getFirebaseAdminServices().db;
  const docs = (snapshot: any) => snapshot.docs.map((doc: any) => ({ id: doc.id, ...doc.data() }));
  return {
    async getUser(id) { const snap = await db.collection("users").doc(id).get(); return snap.exists ? { id: snap.id, ...snap.data() } : null; },
    async getCustomer(type, id) { const snap = await db.collection(type === "PHYSICIAN" ? "physicians" : "pharmacies").doc(id).get(); return snap.exists ? { id: snap.id, ...snap.data() } : null; },
    async getArea(id) { const snap = await db.collection("areas").doc(id).get(); return snap.exists ? { id: snap.id, ...snap.data() } : null; },
    async getMarkets(countryId) { const snap = await db.collection("marketSettings").where("countryId", "==", countryId).where("active", "==", true).get(); return docs(snap).map((market:any)=>({marketId:market.id,...market})) as MarketBusinessSettings[]; },
    async getTerritoryAssignments(userId) { return docs(await db.collection("userTerritoryAssignments").where("userId", "==", userId).get()); },
    async getProductAssignments(userId) { return docs(await db.collection("userProductAssignments").where("userId", "==", userId).get()); },
    async createVisitIdempotently(visit) { const ref=db.collection("supervisorVisits").doc(visit.id); return db.runTransaction(async(tx:Transaction)=>{const existing=await tx.get(ref);if(existing.exists){const row={id:existing.id,...existing.data()} as SupervisorVisit;if(!sameCreateIntent(row,visit))throw new SupervisorVisitError("SUPERVISOR_VISIT_IDEMPOTENCY_CONFLICT",409);return{visit:row,replayed:true};}tx.create(ref,visit);return{visit,replayed:false};}); },
    async listVisits(supervisorId) { return docs(await db.collection("supervisorVisits").where("supervisorId", "==", supervisorId).get()) as SupervisorVisit[]; },
    async listCustomerVisits(customerType, customerId) { return docs(await db.collection("supervisorVisits").where("customerId", "==", customerId).get()).filter((v: SupervisorVisit) => v.customerType === customerType) as SupervisorVisit[]; },
    async getVisit(id) { const snap = await db.collection("supervisorVisits").doc(id).get(); return snap.exists ? ({ id: snap.id, ...snap.data() } as SupervisorVisit) : null; },
    async transitionVisit(id, expectedStatus, updates, voidTransition) { const ref=db.collection("supervisorVisits").doc(id); return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists||snap.data()?.status!==expectedStatus)return null;const current={id:snap.id,...snap.data()} as SupervisorVisit;let appraisalSnap:any=null;if(voidTransition){if(current.coachingAppraisalId!==voidTransition.appraisalId)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);appraisalSnap=await tx.get(db.collection("supervisorCoachingAppraisals").doc(voidTransition.appraisalId));if(!appraisalSnap.exists)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);const appraisal={id:appraisalSnap.id,...appraisalSnap.data()} as SupervisorCoachingAppraisal,phase=effectivePhase(appraisal),revisionNumber=revisionCountOf(appraisal);if(appraisal.status!==voidTransition.expectedStatus||phase!==voidTransition.expectedPhase||revisionNumber!==voidTransition.expectedRevisionNumber)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);if(workflowVersionOf(appraisal)!==voidTransition.expectedWorkflowVersion)throw new SupervisorVisitError("APPRAISAL_WORKFLOW_VERSION_CONFLICT",409);const expectedRole=appraisal.appraisalType==="MEDICAL"?Role.MEDICAL_SUPERVISOR:Role.SALES_SUPERVISOR;if(appraisal.supervisorVisitId!==id||appraisal.supervisorId!==voidTransition.actorUid||appraisal.areaId!==current.areaId||voidTransition.actorRole!==expectedRole)throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);}tx.update(ref,updates);if(appraisalSnap?.exists){const appraisal={id:appraisalSnap.id,...appraisalSnap.data()} as SupervisorCoachingAppraisal,previousPhase=effectivePhase(appraisal)!,previousWorkflowVersion=workflowVersionOf(appraisal),workflowVersion=previousWorkflowVersion+1,revisionNumber=revisionCountOf(appraisal)!;const event={fromStatus:appraisal.status,toStatus:"VOID" as const,action:"VOID" as const,actorUid:voidTransition!.actorUid,actorRole:voidTransition!.actorRole,occurredAt:voidTransition!.occurredAt,fromPhase:previousPhase,toPhase:"VOID" as const,previousWorkflowVersion,workflowVersion,revisionNumber};tx.update(appraisalSnap.ref,{status:"VOID",workflowPhase:"VOID",workflowVersion,voidedAt:voidTransition!.occurredAt,voidedBy:voidTransition!.actorUid,voidReason:"LINKED_SUPERVISOR_VISIT_CANCELLED",updatedAt:voidTransition!.occurredAt,updatedBy:voidTransition!.actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),event]});const audit={...workflowAudit(voidTransition!.auditId,voidTransition!.actorUid,voidTransition!.actorRole,appraisal.id,id,appraisal.status,"VOID","Coaching Appraisal Voided",voidTransition!.occurredAt,previousPhase,"VOID",workflowVersion,undefined,revisionNumber),previousWorkflowVersion};tx.create(db.collection("auditLogs").doc(voidTransition!.auditId),audit);}return {...current,...updates} as SupervisorVisit;}); },
    async rescheduleVisit(id, expectedStatus, updates, audit) { const ref=db.collection("supervisorVisits").doc(id); return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists||snap.data()?.status!==expectedStatus)return null;tx.update(ref,updates);tx.create(db.collection("auditLogs").doc(text(audit.id)),audit);return {id:snap.id,...snap.data(),...updates} as SupervisorVisit;}); },
    async getAppraisal(id){const snap=await db.collection("supervisorCoachingAppraisals").doc(id).get();return snap.exists?({id:snap.id,...snap.data()} as SupervisorCoachingAppraisal):null;},
    async linkAppraisal(visitId, appraisal, audit) { const visitRef = db.collection("supervisorVisits").doc(visitId), appraisalRef = db.collection("supervisorCoachingAppraisals").doc(appraisal.id); return db.runTransaction(async tx => { const snap = await tx.get(visitRef); if (!snap.exists || snap.data()?.status !== "IN_PROGRESS" || snap.data()?.hasCoaching || snap.data()?.coachingAppraisalId) return false; tx.create(appraisalRef, appraisal); tx.update(visitRef, { hasCoaching: true, coachingAppraisalId: appraisal.id, updatedAt: appraisal.updatedAt, updatedBy: appraisal.updatedBy });tx.create(db.collection("auditLogs").doc(text(audit.id)),audit); return true; }); },
    async updateAppraisal(id,expectation,updates,audit){const ref=db.collection("supervisorCoachingAppraisals").doc(id);return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);const current={id:snap.id,...snap.data()} as SupervisorCoachingAppraisal;if(current.status!==expectation.status||effectivePhase(current)!==expectation.phase)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);if(workflowVersionOf(current)!==expectation.workflowVersion)throw new SupervisorVisitError("APPRAISAL_WORKFLOW_VERSION_CONFLICT",409);const roleMatches=expectation.actorKind==="SUPERVISOR"?(current.appraisalType==="MEDICAL"?expectation.actorRole===Role.MEDICAL_SUPERVISOR:expectation.actorRole===Role.SALES_SUPERVISOR):current.representativeRole===expectation.actorRole;if((expectation.actorKind==="SUPERVISOR"?current.supervisorId!==expectation.actorUid:current.representativeId!==expectation.actorUid)||!roleMatches||!expectation.areaIds.includes(current.areaId))throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);const guardCode=expectation.guard?.(current);if(guardCode)throw new SupervisorVisitError(guardCode,409);const finalUpdates={...updates,...(expectation.buildUpdates?.(current)||{})};tx.update(ref,finalUpdates);tx.create(db.collection("auditLogs").doc(text(audit.id)),audit);return{id:snap.id,...snap.data(),...finalUpdates} as SupervisorCoachingAppraisal;});},
    async listSupervisorAppraisals(supervisorId) { return docs(await db.collection("supervisorCoachingAppraisals").where("supervisorId", "==", supervisorId).get()) as SupervisorCoachingAppraisal[]; },
    async listRepresentativeAppraisals(representativeId) { return docs(await db.collection("supervisorCoachingAppraisals").where("representativeId", "==", representativeId).get()) as SupervisorCoachingAppraisal[]; },
  };
}

type SupervisorIdentitySource = { supervisorId:string; supervisorRole?:unknown; appraisalType?:unknown };
const workflowSupervisorRole=(record:SupervisorIdentitySource):Role.MEDICAL_SUPERVISOR|Role.SALES_SUPERVISOR|null=>{
  if(record.supervisorRole!==undefined)return record.supervisorRole===Role.MEDICAL_SUPERVISOR||record.supervisorRole===Role.SALES_SUPERVISOR?record.supervisorRole:null;
  if(record.appraisalType==="MEDICAL")return Role.MEDICAL_SUPERVISOR;
  if(record.appraisalType==="SALES")return Role.SALES_SUPERVISOR;
  return null;
};
export async function resolveSupervisorIdentityPresentations(records:SupervisorIdentitySource[],repo:Pick<SupervisorVisitRepository,"getUser">):Promise<Record<string,SupervisorIdentityPresentation>>{
  const expectedRoles=new Map<string,Role.MEDICAL_SUPERVISOR|Role.SALES_SUPERVISOR>();
  const supervisorIds=new Set<string>(),invalidContexts=new Set<string>();
  for(const record of records){const id=text(record.supervisorId);if(!id)continue;supervisorIds.add(id);const role=workflowSupervisorRole(record),existing=expectedRoles.get(id);if(!role||(existing&&existing!==role))invalidContexts.add(id);else expectedRoles.set(id,role);}
  const entries=await Promise.all([...supervisorIds].map(async id=>{
    const expectedRole=invalidContexts.has(id)?null:expectedRoles.get(id)||null,user=await repo.getUser(id),canonicalRole=text(user?.role),canonicalRoleValid=canonicalRole===Role.MEDICAL_SUPERVISOR||canonicalRole===Role.SALES_SUPERVISOR,name=text(user?.name)||`${text(user?.firstName)} ${text(user?.lastName)}`.trim();
    const resolved=Boolean(user)&&Boolean(expectedRole)&&canonicalRoleValid&&canonicalRole===expectedRole&&Boolean(name);
    const role=resolved?expectedRole:null;
    return [id,{id,name:resolved?name:"Unknown supervisor",role,roleLabel:role,resolved}] as const;
  }));
  return Object.fromEntries(entries);
}

export function parseSupervisorVisitCreate(body: unknown): SupervisorVisitCreate | null {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null; const v = body as any;
  const customerType = text(v.customerType), customerId = text(v.customerId), areaId = text(v.areaId), rep = text(v.accompaniedRepresentativeId), purpose = text(v.purpose), plannedDate = text(v.plannedDate), plannedTime = text(v.plannedTime), objectives = text(v.objectives);
  const idempotencyKey=text(v.idempotencyKey);
  if (Object.keys(v).some(key=>!["customerType","customerId","areaId","accompaniedRepresentativeId","purpose","plannedDate","plannedTime","objectives","idempotencyKey"].includes(key))) return null;
  if (!["PHYSICIAN", "PHARMACY"].includes(customerType) || !customerId || !areaId || !PURPOSES.has(purpose) || !validDate(plannedDate) || !TIME.test(plannedTime) || !objectives || objectives.length > 4000 || !/^[A-Za-z0-9_-]{16,128}$/.test(idempotencyKey)) return null;
  return { customerType: customerType as SupervisorVisitCustomerType, customerId, areaId, accompaniedRepresentativeId: rep || null, purpose: purpose as any, plannedDate, plannedTime, objectives, idempotencyKey };
}

export const supervisorVisitIdForRequest=(actorUid:string,idempotencyKey:string)=>`SUPV-${createHash("sha256").update(`${actorUid}|SUPERVISOR_VISIT_CREATE|${idempotencyKey}`).digest("hex").slice(0,32)}`;

const sameCreateIntent=(existing:SupervisorVisit,requested:SupervisorVisit)=>existing.supervisorId===requested.supervisorId&&existing.supervisorRole===requested.supervisorRole&&existing.customerType===requested.customerType&&existing.customerId===requested.customerId&&existing.areaId===requested.areaId&&(existing.accompaniedRepresentativeId||null)===(requested.accompaniedRepresentativeId||null)&&existing.purpose===requested.purpose&&existing.plannedDate===requested.plannedDate&&existing.plannedTime===requested.plannedTime&&existing.objectives===requested.objectives;
const sameCreateRequest=(existing:SupervisorVisit,actorUid:string,actorRole:string,input:SupervisorVisitCreate)=>existing.supervisorId===actorUid&&existing.supervisorRole===actorRole&&existing.customerType===input.customerType&&existing.customerId===input.customerId&&existing.areaId===input.areaId&&(existing.accompaniedRepresentativeId||null)===(input.accompaniedRepresentativeId||null)&&existing.purpose===input.purpose&&existing.plannedDate===input.plannedDate&&existing.plannedTime===input.plannedTime&&existing.objectives===input.objectives;

export function parseSupervisorVisitReschedule(body: unknown): SupervisorVisitReschedule | null { if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["visitId","plannedDate","plannedTime"].includes(key)))return null;const visitId=text(v.visitId),plannedDate=text(v.plannedDate),plannedTime=text(v.plannedTime);return visitId&&validDate(plannedDate)&&TIME.test(plannedTime)?{visitId,plannedDate,plannedTime}:null; }

async function planningMarket(countryId:string,repo:SupervisorVisitRepository){const markets=(await repo.getMarkets(countryId)).filter(m=>m.active&&validateMarketSettings(m).length===0);if(!markets.length)throw new SupervisorVisitError("SUPERVISOR_VISIT_MARKET_CONFIGURATION_REQUIRED",409);if(markets.length!==1)throw new SupervisorVisitError("SUPERVISOR_VISIT_MARKET_CONFIGURATION_AMBIGUOUS",409);return markets[0];}
function assertNotPast(plannedDate:string,plannedTime:string,market:MarketBusinessSettings,now:string){const localDate=marketDateForInstant(now,market.timezone),localTime=marketTimeForInstant(now,market.timezone);if(plannedDate<localDate||(plannedDate===localDate&&plannedTime<localTime))throw new SupervisorVisitError("SUPERVISOR_VISIT_PLANNED_TIME_IN_PAST",409);}

export function parseSupervisorRepresentativeEligibilityRequest(body: unknown): SupervisorRepresentativeEligibilityRequest | null {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const value = body as Record<string, unknown>;
  if (Object.keys(value).some(key => !["customerType", "customerId", "areaId"].includes(key))) return null;
  const customerType = text(value.customerType), customerId = text(value.customerId), areaId = text(value.areaId);
  if (!["PHYSICIAN", "PHARMACY"].includes(customerType) || !customerId || !areaId) return null;
  return { customerType: customerType as SupervisorVisitCustomerType, customerId, areaId };
}

export function parseSupervisorCustomerVisitHistoryRequest(body: unknown): SupervisorCustomerVisitHistoryRequest | null {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const value = body as Record<string, unknown>;
  if (Object.keys(value).some(key => !["customerType", "customerId", "supervisorRole"].includes(key))) return null;
  const customerType = text(value.customerType), customerId = text(value.customerId), supervisorRole = text(value.supervisorRole);
  if (!["PHYSICIAN", "PHARMACY"].includes(customerType) || !customerId) return null;
  if (supervisorRole && ![Role.MEDICAL_SUPERVISOR, Role.SALES_SUPERVISOR].includes(supervisorRole as Role)) return null;
  return { customerType: customerType as SupervisorVisitCustomerType, customerId, ...(supervisorRole ? { supervisorRole: supervisorRole as Role.MEDICAL_SUPERVISOR | Role.SALES_SUPERVISOR } : {}) };
}

export function parseSupervisorVisitTransition(body: unknown): SupervisorVisitTransition | null {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const value=body as Record<string,unknown>;
  if (Object.keys(value).some(key=>!["visitId","action","outcome","notes"].includes(key))) return null;
  const visitId=text(value.visitId),action=text(value.action) as SupervisorVisitTransitionAction,outcome=text(value.outcome),notes=text(value.notes);
  if(!visitId||!["START","COMPLETE","CANCEL"].includes(action)||outcome.length>4000||notes.length>4000) return null;
  if(action==="COMPLETE"&&!outcome) return null;
  return {visitId,action,outcome,notes};
}

const active = (v: any) => v && v.isDeleted !== true && v.active !== false && !["Inactive", "Archived", "Suspended"].includes(text(v.status));
const activeAssignment = (a: any) => a.active !== false && text(a.status) === "Active";
async function representativeEligibilityFailure(actorRole: string, repId: string, areaId: string, customer: any, scope: any, repo: SupervisorVisitRepository): Promise<string | null> {
  const rep = await repo.getUser(repId), expected = actorRole === Role.MEDICAL_SUPERVISOR ? Role.MEDICAL_REP : Role.SALES_REP;
  if (!active(rep) || rep.role !== expected) return "REPRESENTATIVE_ROLE_DENIED";
  if (!scope.subjectUids.includes(repId) || repId === scope.actorUid) return "REPRESENTATIVE_NOT_DESCENDANT";
  const territory = await repo.getTerritoryAssignments(repId);
  if (!territory.some(a => activeAssignment(a) && canonicalAreaIdForTerritoryAssignment(a) === areaId)) return "REPRESENTATIVE_AREA_DENIED";
  const products = (await repo.getProductAssignments(repId)).filter(activeAssignment);
  if (scope.productIds.length && !products.some(a => scope.productIds.includes(text(a.productId)))) return "REPRESENTATIVE_PRODUCT_DENIED";
  if (customer.primaryPromotionGroupId || Array.isArray(customer.targetPromotionGroupIds)) {
    const groups = new Set([text(customer.primaryPromotionGroupId), ...(customer.targetPromotionGroupIds || []).map(text)].filter(Boolean));
    if (groups.size && !products.some(a => groups.has(text(a.productGroupId)))) return "REPRESENTATIVE_PRODUCT_DENIED";
  }
  return null;
}
async function validateRepresentative(actorRole: string, repId: string | null, areaId: string, customer: any, scope: any, repo: SupervisorVisitRepository) {
  if (!repId) return null;
  const failure = await representativeEligibilityFailure(actorRole, repId, areaId, customer, scope, repo);
  if (failure) throw new SupervisorVisitError(failure);
  return repo.getUser(repId);
}

async function context(actorUid: string, scopeRepo?: OperationalScopeRepository) {
  const scope = await resolveOperationalScopeForActor(actorUid, {}, scopeRepo || createFirestoreOperationalScopeRepository());
  if (!scope.authorized || scope.queryPlan.denyAll || !SUPERVISOR_ROLES.has(scope.role)) throw new SupervisorVisitError(scope.code || "SUPERVISOR_ROLE_DENIED");
  return scope;
}

export async function createSupervisorVisit(actorUid: string, input: SupervisorVisitCreate, deps: { repository?: SupervisorVisitRepository; scopeRepository?: OperationalScopeRepository; now?: () => string; id?: () => string } = {}) {
  const repo = deps.repository || createFirestoreSupervisorVisitRepository(), scope = await context(actorUid, deps.scopeRepository);
  const id=(deps.id||(()=>supervisorVisitIdForRequest(actorUid,input.idempotencyKey)))(),existing=await repo.getVisit(id);
  if(existing){if(existing.supervisorId!==actorUid||existing.supervisorRole!==scope.role||!scope.areaIds.includes(existing.areaId))throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);if(scope.role===Role.SALES_SUPERVISOR&&existing.customerType!=="PHARMACY")throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);if(!sameCreateRequest(existing,actorUid,scope.role,input))throw new SupervisorVisitError("SUPERVISOR_VISIT_IDEMPOTENCY_CONFLICT",409);return{success:true,visit:existing,replayed:true};}
  if (scope.role === Role.SALES_SUPERVISOR && input.customerType === "PHYSICIAN") throw new SupervisorVisitError("SALES_PHYSICIAN_VISIT_DENIED");
  if (!scope.areaIds.includes(input.areaId)) throw new SupervisorVisitError("AREA_SCOPE_DENIED");
  const [customer, area] = await Promise.all([repo.getCustomer(input.customerType, input.customerId), repo.getArea(input.areaId)]);
  if (!active(customer)) throw new SupervisorVisitError("CUSTOMER_NOT_FOUND_OR_INACTIVE", 404);
  if (text(customer.areaId) !== input.areaId) throw new SupervisorVisitError("CUSTOMER_AREA_MISMATCH");
  if (!active(area)) throw new SupervisorVisitError("AREA_NOT_FOUND", 404);
  if (input.customerType === "PHYSICIAN" && scope.productGroupIds.length && ![text(customer.primaryPromotionGroupId), ...(customer.targetPromotionGroupIds || []).map(text)].some(id => scope.productGroupIds.includes(id))) throw new SupervisorVisitError("CUSTOMER_PRODUCT_DENIED");
  const rep = await validateRepresentative(scope.role, input.accompaniedRepresentativeId, input.areaId, customer, scope, repo);
  const now = (deps.now || (() => new Date().toISOString()))(), market=await planningMarket(text(area.countryId),repo);assertNotPast(input.plannedDate,input.plannedTime,market,now);
  const visit: SupervisorVisit = { id, supervisorId: actorUid, supervisorRole: scope.role as any, customerType: input.customerType, customerId: input.customerId, countryId: text(area.countryId), districtId: text(area.districtId), cityId: text(area.cityId), areaId: input.areaId, accompaniedRepresentativeId: rep?.id || null, accompaniedRepresentativeRole: rep?.role || null, purpose: input.purpose, visitDate: input.plannedDate, plannedDate:input.plannedDate,plannedTime:input.plannedTime,planningTimezone:market.timezone, objectives: input.objectives, status: "SCHEDULED", outcome: "", notes: "", hasCoaching: false, coachingAppraisalId: null, createdAt: now, createdBy: actorUid, updatedAt: now, updatedBy: actorUid };
  const created=await repo.createVisitIdempotently(visit); return { success: true, visit:created.visit, replayed:created.replayed };
}

export async function rescheduleSupervisorVisit(actorUid:string,input:SupervisorVisitReschedule,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;id?:()=>string}={}){const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await context(actorUid,deps.scopeRepository),visit=await repo.getVisit(input.visitId);if(!visit||visit.supervisorId!==actorUid||visit.supervisorRole!==scope.role||!scope.areaIds.includes(visit.areaId))throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);if(visit.status!=="SCHEDULED")throw new SupervisorVisitError("SUPERVISOR_VISIT_RESCHEDULE_REQUIRES_SCHEDULED",409);if(!hasCanonicalSchedule(visit))throw new SupervisorVisitError("SUPERVISOR_VISIT_CANONICAL_SCHEDULE_REQUIRED",409);const market=await planningMarket(visit.countryId,repo),now=(deps.now||(()=>new Date().toISOString()))();assertNotPast(input.plannedDate,input.plannedTime,market,now);const previousPlannedDate=visit.plannedDate!,previousPlannedTime=visit.plannedTime!;const updates:Partial<SupervisorVisit>={visitDate:input.plannedDate,plannedDate:input.plannedDate,plannedTime:input.plannedTime,planningTimezone:market.timezone,updatedAt:now,updatedBy:actorUid};const auditId=(deps.id||(()=>`AUD-SUPV-${randomUUID()}`))(),audit={id:auditId,userId:actorUid,userRole:scope.role,action:"Supervisor Visit Rescheduled",entityType:"SupervisorVisit",entityId:visit.id,previousPlannedDate,previousPlannedTime,plannedDate:input.plannedDate,plannedTime:input.plannedTime,timezone:market.timezone,timestamp:now,createdAt:now,createdBy:actorUid};const updated=await repo.rescheduleVisit(visit.id,"SCHEDULED",updates,audit);if(!updated)throw new SupervisorVisitError("VISIT_STATE_CHANGED",409);return{success:true,visit:updated};}

export async function transitionSupervisorVisit(actorUid:string,input:SupervisorVisitTransition,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await context(actorUid,deps.scopeRepository),visit=await repo.getVisit(input.visitId);
  if(!visit||visit.supervisorId!==actorUid||visit.supervisorRole!==scope.role||!scope.areaIds.includes(visit.areaId)) throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);
  if(scope.role===Role.SALES_SUPERVISOR&&visit.customerType!=="PHARMACY") throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);
  const transition=input.action==="START"?{from:"SCHEDULED" as const,to:"IN_PROGRESS" as const}:input.action==="COMPLETE"?{from:"IN_PROGRESS" as const,to:"COMPLETED" as const}:["SCHEDULED","IN_PROGRESS"].includes(visit.status)?{from:visit.status as "SCHEDULED"|"IN_PROGRESS",to:"CANCELLED" as const}:null;
  if(!transition||visit.status!==transition.from) throw new SupervisorVisitError("INVALID_VISIT_STATE_TRANSITION",409);
  if(input.action==="START"&&!hasCanonicalSchedule(visit)) throw new SupervisorVisitError("SUPERVISOR_VISIT_CANONICAL_SCHEDULE_REQUIRED",409);
  const now=(deps.now||(()=>new Date().toISOString()))(),event={fromStatus:transition.from,toStatus:transition.to,action:input.action,actorUid,occurredAt:now};
  const updates:Partial<SupervisorVisit>={status:transition.to,updatedAt:now,updatedBy:actorUid,lifecycleHistory:[...(visit.lifecycleHistory||[]),event],...(input.notes?{notes:input.notes}:{}),...(input.outcome?{outcome:input.outcome}:{}),...(input.action==="START"?{startedAt:now,startedBy:actorUid}:input.action==="COMPLETE"?{completedAt:now,completedBy:actorUid}:{cancelledAt:now,cancelledBy:actorUid})};
  let voidTransition:AppraisalVoidExpectation|undefined;
  if(input.action==="CANCEL"&&visit.coachingAppraisalId){const appraisal=await repo.getAppraisal(visit.coachingAppraisalId);if(appraisal&&["DRAFT","PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED"].includes(appraisal.status)){const expectedPhase=effectivePhase(appraisal),expectedRevisionNumber=revisionCountOf(appraisal);if(!expectedPhase||expectedRevisionNumber===null)throw new SupervisorVisitError("APPRAISAL_STATE_CHANGED",409);const expectedRole=appraisal.appraisalType==="MEDICAL"?Role.MEDICAL_SUPERVISOR:Role.SALES_SUPERVISOR;if(appraisal.supervisorVisitId!==visit.id||appraisal.supervisorId!==actorUid||appraisal.areaId!==visit.areaId||scope.role!==expectedRole)throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);voidTransition={actorUid,actorRole:scope.role as Role,occurredAt:now,auditId:`AUD-COACH-${randomUUID()}`,appraisalId:appraisal.id,expectedStatus:appraisal.status,expectedPhase,expectedWorkflowVersion:workflowVersionOf(appraisal),expectedRevisionNumber};}}
  const updated=await repo.transitionVisit(visit.id,transition.from,updates,voidTransition);
  if(!updated) throw new SupervisorVisitError("VISIT_STATE_CHANGED",409);
  return {success:true,visit:updated};
}

export async function readEligibleSupervisorRepresentatives(actorUid: string, input: SupervisorRepresentativeEligibilityRequest, deps: { repository?: SupervisorVisitRepository; scopeRepository?: OperationalScopeRepository } = {}) {
  const repo = deps.repository || createFirestoreSupervisorVisitRepository(), scope = await context(actorUid, deps.scopeRepository);
  if (scope.role === Role.SALES_SUPERVISOR && input.customerType === "PHYSICIAN") throw new SupervisorVisitError("SALES_PHYSICIAN_VISIT_DENIED");
  if (!scope.areaIds.includes(input.areaId)) throw new SupervisorVisitError("AREA_SCOPE_DENIED");
  const customer = await repo.getCustomer(input.customerType, input.customerId);
  if (!active(customer)) throw new SupervisorVisitError("CUSTOMER_NOT_FOUND_OR_INACTIVE", 404);
  if (text(customer.areaId) !== input.areaId) throw new SupervisorVisitError("CUSTOMER_AREA_MISMATCH");
  if (input.customerType === "PHYSICIAN" && scope.productGroupIds.length && ![text(customer.primaryPromotionGroupId), ...(customer.targetPromotionGroupIds || []).map(text)].some(id => scope.productGroupIds.includes(id))) throw new SupervisorVisitError("CUSTOMER_PRODUCT_DENIED");
  const representatives = (await Promise.all(scope.subjectUids.filter(id => id !== scope.actorUid).map(async id => {
    if (await representativeEligibilityFailure(scope.role, id, input.areaId, customer, scope, repo)) return null;
    const user = await repo.getUser(id);
    return user ? { id: user.id, name: text(user.name) || user.id, role: user.role } : null;
  }))).filter((value): value is { id: string; name: string; role: Role } => Boolean(value)).sort((a,b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
  return { authorized: true, representatives };
}

export async function readSupervisorVisits(actorUid: string, filter: { customerType?: SupervisorVisitCustomerType; customerId?: string; supervisorRole?: Role.MEDICAL_SUPERVISOR | Role.SALES_SUPERVISOR } = {}, deps: { repository?: SupervisorVisitRepository; scopeRepository?: OperationalScopeRepository } = {}) {
  const repo = deps.repository || createFirestoreSupervisorVisitRepository(), scope = await context(actorUid, deps.scopeRepository);
  const rows = filter.customerId ? await repo.listCustomerVisits(filter.customerType!, filter.customerId) : await repo.listVisits(actorUid);
  const visits = rows.filter(v => scope.areaIds.includes(v.areaId) && (!filter.customerType || v.customerType === filter.customerType) && (!filter.customerId || v.customerId === filter.customerId) && (!filter.supervisorRole || v.supervisorRole === filter.supervisorRole) && (filter.customerId || v.supervisorId === actorUid) && (scope.role !== Role.SALES_SUPERVISOR || v.customerType === "PHARMACY"));
  return { authorized: true, visits: visits.sort((a,b) => b.visitDate.localeCompare(a.visitDate) || a.id.localeCompare(b.id)) };
}

export async function readSupervisorCustomerVisitHistory(actorUid: string, input: SupervisorCustomerVisitHistoryRequest, deps: { repository?: SupervisorVisitRepository; scopeRepository?: OperationalScopeRepository } = {}) {
  const repo = deps.repository || createFirestoreSupervisorVisitRepository();
  const scopeRepository = deps.scopeRepository || createFirestoreOperationalScopeRepository();
  const scope = await resolveOperationalScopeForActor(actorUid, {}, scopeRepository);
  if (!scope.authorized || scope.queryPlan.denyAll) throw new SupervisorVisitError(scope.code || "SUPERVISOR_HISTORY_SCOPE_DENIED");
  const customer = await repo.getCustomer(input.customerType, input.customerId);
  if (!active(customer)) throw new SupervisorVisitError("CUSTOMER_NOT_FOUND_OR_INACTIVE", 404);
  const customerAreaId = text(customer.areaId);
  const customerVisible = input.customerType === "PHYSICIAN" ? filterPhysiciansWithinOperationalScope([customer], scope).length === 1 : filterPharmaciesWithinOperationalScope([customer], scope).length === 1;
  if (!customerAreaId || !customerVisible) throw new SupervisorVisitError("CUSTOMER_HISTORY_SCOPE_DENIED", 403);
  const rows = await repo.listCustomerVisits(input.customerType, input.customerId);
  const visits = rows.filter(visit => visit.customerType === input.customerType && visit.customerId === input.customerId && visit.areaId === customerAreaId && scope.areaIds.includes(visit.areaId) && (!input.supervisorRole || visit.supervisorRole === input.supervisorRole));
  const catalog = await scopeRepository.getGeographyCatalog(), countries = new Map(catalog.countries.map(row => [row.id, row.name || row.id])), districts = new Map(catalog.districts.map(row => [row.id, row.name || row.id])), cities = new Map(catalog.cities.map(row => [row.id, row.name || row.id]));
  const visitAreaIds = new Set(visits.map(visit => visit.areaId));
  const areas = catalog.areas.filter(area => visitAreaIds.has(area.id) && scope.areaIds.includes(area.id)).map(area => ({ id:area.id, name:area.name || area.id, countryId:text(area.countryId), countryName:countries.get(text(area.countryId)) || text(area.countryId), districtId:text(area.districtId), districtName:districts.get(text(area.districtId)) || text(area.districtId), cityId:text(area.cityId), cityName:cities.get(text(area.cityId)) || text(area.cityId) }));
  const sortedVisits=visits.sort((a,b) => b.visitDate.localeCompare(a.visitDate) || a.id.localeCompare(b.id));
  return { authorized:true, visits:sortedVisits, areas, supervisors:await resolveSupervisorIdentityPresentations(sortedVisits,repo) };
}

const DRAFT_KEYS=["sections","sectionWeights","scores","comments","sectionNotes","strengths","improvementAreas","actionPlan","recommendations","overallRating"] as const;
const DRAFT_SAVE_KEYS=["sections","scores","comments","sectionNotes","strengths","improvementAreas","actionPlan","recommendations","overallRating"] as const;
const REVISION_KEYS=["scores","comments","sectionNotes","strengths","improvementAreas","actionPlan","recommendations","overallRating"] as const;
const CANONICAL_COACHING_SECTION_KEYS=new Set(["knowledge","communication","professionalism","productivity","salesKnowledge","salesExecution","salesQuality","development"]);
const WORKFLOW_PHASES=new Set<SupervisorCoachingWorkflowPhase>(["INITIAL_DRAFT","INITIAL_REPRESENTATIVE_REVIEW","SUPERVISOR_DISAGREEMENT_REVIEW","REVISION_DRAFT","FINAL_REPRESENTATIVE_REVIEW","SUPERVISOR_FINAL_REVIEW","FINALIZED","VOID"]);
const validExpectedVersion=(value:unknown):value is number=>Number.isInteger(value)&&Number(value)>=0;
function workflowVersionOf(appraisal:SupervisorCoachingAppraisal){return Number.isInteger(appraisal.workflowVersion)&&Number(appraisal.workflowVersion)>=0?Number(appraisal.workflowVersion):0;}
function revisionCountOf(appraisal:SupervisorCoachingAppraisal):0|1|null{if(appraisal.preRevisionSnapshot)return appraisal.revisionCount===1?1:null;if(appraisal.revisionCount===undefined||appraisal.revisionCount===0)return 0;return null;}
export function effectiveSupervisorCoachingPhase(appraisal:SupervisorCoachingAppraisal):SupervisorCoachingWorkflowPhase|null{
  const revisionCount=revisionCountOf(appraisal);if(revisionCount===null)return null;
  if(appraisal.workflowPhase!==undefined)return WORKFLOW_PHASES.has(appraisal.workflowPhase)?appraisal.workflowPhase:null;
  if(appraisal.status==="SIGNED_OFF")return "FINALIZED";if(appraisal.status==="VOID")return "VOID";if(appraisal.status==="COMPLETED")return null;
  if(appraisal.status==="DRAFT")return appraisal.preRevisionSnapshot&&revisionCount===1?"REVISION_DRAFT":!appraisal.representativeReviewDecision?"INITIAL_DRAFT":null;
  if(appraisal.status==="PENDING_CONFIRMATION")return appraisal.preRevisionSnapshot&&revisionCount===1?"FINAL_REPRESENTATIVE_REVIEW":!appraisal.finalRepresentativeReviewDecision?"INITIAL_REPRESENTATIVE_REVIEW":null;
  if(appraisal.status==="REPRESENTATIVE_REVIEWED"){
    if(appraisal.finalRepresentativeReviewDecision)return appraisal.preRevisionSnapshot&&revisionCount===1?"SUPERVISOR_FINAL_REVIEW":null;
    if(appraisal.representativeReviewDecision==="ACKNOWLEDGED")return "SUPERVISOR_FINAL_REVIEW";
    if(appraisal.representativeReviewDecision==="DISAGREE_REQUEST_REVIEW")return appraisal.supervisorDisagreementResolution==="KEEP_UNCHANGED"?"SUPERVISOR_FINAL_REVIEW":!appraisal.supervisorDisagreementResolution?"SUPERVISOR_DISAGREEMENT_REVIEW":null;
  }
  return null;
}
const effectivePhase=effectiveSupervisorCoachingPhase;
function parseDraftFields(v:any):AppraisalDraftFields|null{
  const scores=v.scores,comments=v.comments,sectionWeights=v.sectionWeights,sectionNotes=v.sectionNotes;
  if(!Array.isArray(v.sections)||!scores||typeof scores!=="object"||Array.isArray(scores)||!comments||typeof comments!=="object"||Array.isArray(comments)||(sectionWeights!==undefined&&(!sectionWeights||typeof sectionWeights!=="object"||Array.isArray(sectionWeights)))||(sectionNotes!==undefined&&(!sectionNotes||typeof sectionNotes!=="object"||Array.isArray(sectionNotes)))||!Number.isFinite(v.overallRating)||v.overallRating<0||v.overallRating>5)return null;
  if(Object.keys(sectionWeights||{}).some(key=>!CANONICAL_COACHING_SECTION_KEYS.has(key))||Object.values(sectionWeights||{}).some(weight=>!Number.isFinite(weight)||Number(weight)<=0||Number(weight)>100)||Object.values(scores).some(score=>!Number.isFinite(score)||Number(score)<1||Number(score)>5)||Object.values(comments).some(value=>typeof value!=="string")||Object.values(sectionNotes||{}).some(value=>typeof value!=="string"))return null;
  const sections=v.sections.map((section:any)=>({id:text(section?.id),title:text(section?.title),criteria:Array.isArray(section?.criteria)?section.criteria.map(text):[]}));
  if(sections.some((section:any)=>!section.id||!section.title||section.criteria.some((id:string)=>!id)))return null;
  return{sections,sectionWeights:sectionWeights||{},scores,comments,sectionNotes:sectionNotes||{},strengths:text(v.strengths),improvementAreas:text(v.improvementAreas),actionPlan:text(v.actionPlan),recommendations:text(v.recommendations),overallRating:v.overallRating};
}
export function parseAppraisalCreate(body:unknown):AppraisalCreate|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["supervisorVisitId","appraisalType",...DRAFT_KEYS].includes(key as any)))return null;const fields=parseDraftFields(v),supervisorVisitId=text(v.supervisorVisitId);return fields&&supervisorVisitId&&["MEDICAL","SALES"].includes(v.appraisalType)?{supervisorVisitId,appraisalType:v.appraisalType,...fields}:null;}
export function parseAppraisalDraftSave(body:unknown):AppraisalDraftSave|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["appraisalId","expectedWorkflowVersion",...DRAFT_SAVE_KEYS].includes(key as any))||!validExpectedVersion(v.expectedWorkflowVersion))return null;const appraisalId=text(v.appraisalId),fields=parseDraftFields(v);if(!appraisalId||!fields)return null;const{sectionWeights:_,...editable}=fields;return{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion,...editable};}
export function parseAppraisalSubmit(body:unknown):AppraisalSubmit|null{if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body).some(key=>!["appraisalId","expectedWorkflowVersion"].includes(key)))return null;const v=body as any,appraisalId=text(v.appraisalId);return appraisalId&&validExpectedVersion(v.expectedWorkflowVersion)?{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion}:null;}
export function parseAppraisalRepresentativeReview(body:unknown):AppraisalRepresentativeReview|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["appraisalId","expectedWorkflowVersion","reviewDecision","representativeComment"].includes(key))||!validExpectedVersion(v.expectedWorkflowVersion))return null;const appraisalId=text(v.appraisalId),reviewDecision=text(v.reviewDecision) as SupervisorCoachingReviewDecision,representativeComment=text(v.representativeComment);if(!appraisalId||!["ACKNOWLEDGED","DISAGREE_REQUEST_REVIEW"].includes(reviewDecision)||representativeComment.length>4000||(reviewDecision==="DISAGREE_REQUEST_REVIEW"&&!representativeComment))return null;return{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion,reviewDecision,representativeComment};}
export function parseAppraisalKeepUnchanged(body:unknown):AppraisalKeepUnchanged|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["appraisalId","expectedWorkflowVersion","supervisorRationale"].includes(key))||!validExpectedVersion(v.expectedWorkflowVersion))return null;const appraisalId=text(v.appraisalId),supervisorRationale=text(v.supervisorRationale);return appraisalId&&supervisorRationale&&supervisorRationale.length<=4000?{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion,supervisorRationale}:null;}
export function parseAppraisalOpenRevision(body:unknown):AppraisalOpenRevision|null{return parseAppraisalSubmit(body);}
function parseRevisionFields(v:any):AppraisalRevisionFields|null{const scores=v.scores,comments=v.comments,sectionNotes=v.sectionNotes;if(!scores||typeof scores!=="object"||Array.isArray(scores)||!comments||typeof comments!=="object"||Array.isArray(comments)||!sectionNotes||typeof sectionNotes!=="object"||Array.isArray(sectionNotes)||!Number.isFinite(v.overallRating)||v.overallRating<0||v.overallRating>5)return null;if(Object.values(scores).some(score=>!Number.isFinite(score)||Number(score)<1||Number(score)>5)||Object.values(comments).some(value=>typeof value!=="string")||Object.values(sectionNotes).some(value=>typeof value!=="string"))return null;return{scores,comments,sectionNotes,strengths:text(v.strengths),improvementAreas:text(v.improvementAreas),actionPlan:text(v.actionPlan),recommendations:text(v.recommendations),overallRating:v.overallRating};}
export function parseAppraisalRevisionSave(body:unknown):AppraisalRevisionSave|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["appraisalId","expectedWorkflowVersion",...REVISION_KEYS].includes(key as any))||!validExpectedVersion(v.expectedWorkflowVersion))return null;const appraisalId=text(v.appraisalId),fields=parseRevisionFields(v);return appraisalId&&fields?{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion,...fields}:null;}
export function parseAppraisalFinalRepresentativeReview(body:unknown):AppraisalFinalRepresentativeReview|null{if(!body||typeof body!=="object"||Array.isArray(body))return null;const v=body as any;if(Object.keys(v).some(key=>!["appraisalId","expectedWorkflowVersion","reviewDecision","representativeComment"].includes(key))||!validExpectedVersion(v.expectedWorkflowVersion))return null;const appraisalId=text(v.appraisalId),reviewDecision=text(v.reviewDecision) as SupervisorCoachingFinalReviewDecision,representativeComment=text(v.representativeComment);if(!appraisalId||reviewDecision!=="ACKNOWLEDGE_REVISED_APPRAISAL"||representativeComment.length>4000)return null;return{appraisalId,expectedWorkflowVersion:v.expectedWorkflowVersion,reviewDecision,representativeComment};}
export const parseAppraisalSignOff=parseAppraisalSubmit;
function workflowAudit(id:string,actorUid:string,actorRole:Role,appraisalId:string,visitId:string,previousState:string,newState:string,action:string,timestamp:string,previousPhase?:SupervisorCoachingWorkflowPhase|null,newPhase?:SupervisorCoachingWorkflowPhase,workflowVersion?:number,reviewDecision?:SupervisorCoachingReviewDecision|SupervisorCoachingFinalReviewDecision,revisionNumber?:number){return{id,userId:actorUid,userRole:actorRole,actorUid,actorRole,action,entityType:"SupervisorCoachingAppraisal",entityId:appraisalId,appraisalId,supervisorVisitId:visitId,previousState,newState,...(previousPhase?{previousPhase}:{}),...(newPhase?{newPhase}:{}),...(workflowVersion!==undefined?{workflowVersion}:{}),...(reviewDecision?{reviewDecision}:{}),...(revisionNumber!==undefined?{revisionNumber}:{}),timestamp,createdAt:timestamp,createdBy:actorUid};}
function workflowEvent(fromStatus:SupervisorCoachingStatus|"NEW",toStatus:SupervisorCoachingStatus,action:"CREATE"|"SAVE_DRAFT"|"SUBMIT"|"REPRESENTATIVE_REVIEW"|"KEEP_UNCHANGED"|"OPEN_REVISION"|"SAVE_REVISION"|"SUBMIT_REVISION"|"FINAL_REPRESENTATIVE_REVIEW"|"SIGN_OFF",actorUid:string,actorRole:Role,occurredAt:string,fromPhase?:SupervisorCoachingWorkflowPhase,toPhase?:SupervisorCoachingWorkflowPhase,reviewDecision?:SupervisorCoachingReviewDecision|SupervisorCoachingFinalReviewDecision,revisionNumber?:number){return{fromStatus,toStatus,action,actorUid,actorRole,occurredAt,...(fromPhase?{fromPhase}:{}),...(toPhase?{toPhase}:{}),...(reviewDecision?{reviewDecision}:{}),...(revisionNumber!==undefined?{revisionNumber}: {})};}
const REQUIRED_COACHING_CRITERIA={
  MEDICAL:["productKnowledge","therapyKnowledge","marketKnowledge","preCall","rapport","detailing","objections","closing","appearance","ethics","medicalVisits","callQuality","coverage"],
  SALES:["salesProductKnowledge","salesPreparation","pharmacyQuality","orderExecution","collectionsExecution","availability","salesCallQuality","salesCoverage","salesEthics","developmentPlan"],
} as const;
const CANONICAL_SECTION_WEIGHTS={MEDICAL:{knowledge:35,communication:25,professionalism:10,productivity:30},SALES:{salesKnowledge:20,salesExecution:40,salesQuality:30,development:10}} as const;
// The canonical appraisal discriminator remains scope.role === Role.MEDICAL_SUPERVISOR.
function appraisalComplete(appraisal:SupervisorCoachingAppraisal){return REQUIRED_COACHING_CRITERIA[appraisal.appraisalType].every(id=>Number.isFinite(appraisal.scores[id])&&appraisal.scores[id]>=1&&appraisal.scores[id]<=5);}
async function supervisorAppraisalContext(actorUid:string,appraisalId:string,repo:SupervisorVisitRepository,scopeRepo?:OperationalScopeRepository){const scope=await context(actorUid,scopeRepo),appraisal=await repo.getAppraisal(appraisalId);if(!appraisal||appraisal.supervisorId!==actorUid||!scope.areaIds.includes(appraisal.areaId))throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);const expectedRole=appraisal.appraisalType==="MEDICAL"?Role.MEDICAL_SUPERVISOR:Role.SALES_SUPERVISOR;if(scope.role!==expectedRole)throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);return{scope,appraisal};}
async function coachingActor(actorUid:string,scopeRepo?:OperationalScopeRepository){const scope=await resolveOperationalScopeForActor(actorUid,{},scopeRepo||createFirestoreOperationalScopeRepository());if(!scope.authorized||scope.queryPlan.denyAll||![Role.MEDICAL_SUPERVISOR,Role.SALES_SUPERVISOR,Role.MEDICAL_REP,Role.SALES_REP].includes(scope.role as Role))throw new SupervisorVisitError(scope.code||"COACHING_ROLE_DENIED");return scope;}
const mutationExpectation=(appraisal:SupervisorCoachingAppraisal,input:{expectedWorkflowVersion:number},actorUid:string,actorKind:"SUPERVISOR"|"REPRESENTATIVE",scope:{role?:string;areaIds:string[]},status:SupervisorCoachingStatus,phase:SupervisorCoachingWorkflowPhase,guard?:(current:SupervisorCoachingAppraisal)=>string|null):AppraisalMutationExpectation=>{
  if(appraisal.status!==status||effectivePhase(appraisal)!==phase)throw new SupervisorVisitError("INVALID_APPRAISAL_STATE_TRANSITION",409);
  if(workflowVersionOf(appraisal)!==input.expectedWorkflowVersion)throw new SupervisorVisitError("APPRAISAL_WORKFLOW_VERSION_CONFLICT",409);
  return{status,phase,workflowVersion:input.expectedWorkflowVersion,actorUid,actorKind,actorRole:text(scope.role),areaIds:scope.areaIds,guard};
};
const nextVersion=(appraisal:SupervisorCoachingAppraisal)=>workflowVersionOf(appraisal)+1;
const revisionGuard=(current:SupervisorCoachingAppraisal)=>revisionCountOf(current)===1&&current.preRevisionSnapshot&&current.supervisorDisagreementResolution==="REVISE"?null:"APPRAISAL_REVISION_STATE_INVALID";

export async function createSupervisorAppraisal(actorUid:string,input:AppraisalCreate,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;id?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await context(actorUid,deps.scopeRepository),visit=await repo.getVisit(input.supervisorVisitId);
  if(!visit||visit.supervisorId!==actorUid||visit.supervisorRole!==scope.role||!scope.areaIds.includes(visit.areaId))throw new SupervisorVisitError("VISIT_NOT_FOUND_OR_DENIED",404);
  if(visit.purpose!=="Coaching Session"||!visit.accompaniedRepresentativeId||!visit.accompaniedRepresentativeRole)throw new SupervisorVisitError("VISIT_NOT_COACHABLE");if(visit.status!=="IN_PROGRESS")throw new SupervisorVisitError("COACHING_REQUIRES_IN_PROGRESS",409);
  if(visit.coachingAppraisalId){const existing=await repo.getAppraisal(visit.coachingAppraisalId);if(existing&&existing.supervisorId===actorUid)return{success:true,appraisal:existing,replayed:true};throw new SupervisorVisitError("APPRAISAL_ALREADY_LINKED",409);}
  const expectedType=scope.role===Role.MEDICAL_SUPERVISOR?"MEDICAL":"SALES",expectedRole=scope.role===Role.MEDICAL_SUPERVISOR?Role.MEDICAL_REP:Role.SALES_REP;if(input.appraisalType!==expectedType||visit.accompaniedRepresentativeRole!==expectedRole)throw new SupervisorVisitError("APPRAISAL_ROLE_DENIED");
  const now=(deps.now||(()=>new Date().toISOString()))(),id=(deps.id||(()=>`COACH-${randomUUID()}`))(),event=workflowEvent("NEW","DRAFT","CREATE",actorUid,scope.role as Role,now,undefined,"INITIAL_DRAFT",undefined,0);
  const appraisal:SupervisorCoachingAppraisal={...input,sectionWeights:{...CANONICAL_SECTION_WEIGHTS[input.appraisalType]},id,supervisorId:actorUid,representativeId:visit.accompaniedRepresentativeId,representativeRole:visit.accompaniedRepresentativeRole,customerType:visit.customerType,customerId:visit.customerId,areaId:visit.areaId,visitDate:visit.visitDate,status:"DRAFT",workflowPhase:"INITIAL_DRAFT",workflowVersion:0,revisionCount:0,workflowHistory:[event],createdAt:now,createdBy:actorUid,updatedAt:now,updatedBy:actorUid};
  const auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),audit=workflowAudit(auditId,actorUid,scope.role as Role,id,visit.id,"NEW","DRAFT","Coaching Appraisal Created",now,null,"INITIAL_DRAFT",0,undefined,0);if(!await repo.linkAppraisal(visit.id,appraisal,audit))throw new SupervisorVisitError("APPRAISAL_ALREADY_LINKED",409);return{success:true,appraisal,replayed:false};
}
export async function saveSupervisorAppraisalDraft(actorUid:string,input:AppraisalDraftSave,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"DRAFT","INITIAL_DRAFT",current=>!current.representativeReviewDecision&&revisionCountOf(current)===0&&!current.preRevisionSnapshot?null:"APPRAISAL_STATE_CHANGED"),visit=await repo.getVisit(appraisal.supervisorVisitId);
  if(!visit||!["IN_PROGRESS","COMPLETED"].includes(visit.status))throw new SupervisorVisitError("APPRAISAL_EDIT_REQUIRES_ACTIVE_OR_COMPLETED_VISIT",409);
  const now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),{appraisalId:_,expectedWorkflowVersion:__,...fields}=input,event=workflowEvent("DRAFT","DRAFT","SAVE_DRAFT",actorUid,scope.role as Role,now,"INITIAL_DRAFT","INITIAL_DRAFT",undefined,0),updates={...fields,workflowPhase:"INITIAL_DRAFT" as const,workflowVersion:version,revisionCount:0 as const,workflowHistory:[...(appraisal.workflowHistory||[]),event],updatedAt:now,updatedBy:actorUid},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"DRAFT","DRAFT","Coaching Draft Saved",now,"INITIAL_DRAFT","INITIAL_DRAFT",version,undefined,0));return{success:true,appraisal:updated!};
}
export async function submitSupervisorAppraisal(actorUid:string,input:AppraisalSubmit,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"DRAFT","INITIAL_DRAFT",current=>revisionCountOf(current)===0&&!current.preRevisionSnapshot&&!current.representativeReviewDecision?null:"APPRAISAL_STATE_CHANGED"),visit=await repo.getVisit(appraisal.supervisorVisitId);if(!visit||!["IN_PROGRESS","COMPLETED"].includes(visit.status))throw new SupervisorVisitError("APPRAISAL_SUBMIT_VISIT_STATE_DENIED",409);if(!appraisalComplete(appraisal))throw new SupervisorVisitError("APPRAISAL_INCOMPLETE",409);
  const now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),updates={status:"PENDING_CONFIRMATION" as const,workflowPhase:"INITIAL_REPRESENTATIVE_REVIEW" as const,workflowVersion:version,submittedAt:now,submittedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("DRAFT","PENDING_CONFIRMATION","SUBMIT",actorUid,scope.role as Role,now,"INITIAL_DRAFT","INITIAL_REPRESENTATIVE_REVIEW",undefined,0)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"DRAFT","PENDING_CONFIRMATION","Coaching Appraisal Submitted",now,"INITIAL_DRAFT","INITIAL_REPRESENTATIVE_REVIEW",version,undefined,0));return{success:true,appraisal:updated!};
}
export async function reviewSupervisorAppraisal(actorUid:string,input:AppraisalRepresentativeReview,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await coachingActor(actorUid,deps.scopeRepository);if(![Role.MEDICAL_REP,Role.SALES_REP].includes(scope.role as Role))throw new SupervisorVisitError("REPRESENTATIVE_REVIEW_ROLE_DENIED");const appraisal=await repo.getAppraisal(input.appraisalId);if(!appraisal||appraisal.representativeId!==actorUid||appraisal.representativeRole!==scope.role)throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);
  const expectation=mutationExpectation(appraisal,input,actorUid,"REPRESENTATIVE",scope,"PENDING_CONFIRMATION","INITIAL_REPRESENTATIVE_REVIEW",current=>!current.representativeReviewDecision&&revisionCountOf(current)===0&&!current.preRevisionSnapshot?null:"APPRAISAL_REVIEW_ALREADY_RECORDED"),now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),phase=input.reviewDecision==="ACKNOWLEDGED"?"SUPERVISOR_FINAL_REVIEW":"SUPERVISOR_DISAGREEMENT_REVIEW",updates={status:"REPRESENTATIVE_REVIEWED" as const,workflowPhase:phase as SupervisorCoachingWorkflowPhase,workflowVersion:version,representativeReviewDecision:input.reviewDecision,representativeComment:input.representativeComment,representativeReviewedAt:now,representativeReviewedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED","REPRESENTATIVE_REVIEW",actorUid,scope.role as Role,now,"INITIAL_REPRESENTATIVE_REVIEW",phase,input.reviewDecision,0)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED","Coaching Appraisal Representative Reviewed",now,"INITIAL_REPRESENTATIVE_REVIEW",phase,version,input.reviewDecision,0));return{success:true,appraisal:updated!};
}
export async function keepSupervisorAppraisalUnchanged(actorUid:string,input:AppraisalKeepUnchanged,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  if(!text(input.supervisorRationale)||input.supervisorRationale.length>4000)throw new SupervisorVisitError("SUPERVISOR_RATIONALE_REQUIRED",400);const rationale=text(input.supervisorRationale),repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),guard=(current:SupervisorCoachingAppraisal)=>current.representativeReviewDecision==="DISAGREE_REQUEST_REVIEW"&&Boolean(text(current.representativeComment))&&revisionCountOf(current)===0&&!current.preRevisionSnapshot&&!current.supervisorDisagreementResolution?null:"APPRAISAL_DISAGREEMENT_ALREADY_RESOLVED",expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"REPRESENTATIVE_REVIEWED","SUPERVISOR_DISAGREEMENT_REVIEW",guard),now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),event={...workflowEvent("REPRESENTATIVE_REVIEWED","REPRESENTATIVE_REVIEWED","KEEP_UNCHANGED",actorUid,scope.role as Role,now,"SUPERVISOR_DISAGREEMENT_REVIEW","SUPERVISOR_FINAL_REVIEW",undefined,0),supervisorRationale:rationale},updates={workflowPhase:"SUPERVISOR_FINAL_REVIEW" as const,workflowVersion:version,supervisorDisagreementResolution:"KEEP_UNCHANGED" as const,supervisorDisagreementRationale:rationale,supervisorDisagreementResolvedAt:now,supervisorDisagreementResolvedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),event]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),audit={...workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"REPRESENTATIVE_REVIEWED","REPRESENTATIVE_REVIEWED","Coaching Appraisal Kept Unchanged",now,"SUPERVISOR_DISAGREEMENT_REVIEW","SUPERVISOR_FINAL_REVIEW",version,undefined,0),supervisorRationale:rationale},updated=await repo.updateAppraisal(appraisal.id,expectation,updates,audit);return{success:true,appraisal:updated!};
}
export async function openSupervisorAppraisalRevision(actorUid:string,input:AppraisalOpenRevision,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),guard=(current:SupervisorCoachingAppraisal)=>current.representativeReviewDecision==="DISAGREE_REQUEST_REVIEW"&&Boolean(text(current.representativeComment))&&revisionCountOf(current)===0&&!current.preRevisionSnapshot&&!current.supervisorDisagreementResolution?null:"APPRAISAL_REVISION_ALREADY_USED",expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"REPRESENTATIVE_REVIEWED","SUPERVISOR_DISAGREEMENT_REVIEW",guard),now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal);
  expectation.buildUpdates=current=>({preRevisionSnapshot:{sections:current.sections.map(section=>({...section,criteria:[...section.criteria]})),sectionWeights:{...(current.sectionWeights||{})},scores:{...current.scores},comments:{...current.comments},sectionNotes:{...(current.sectionNotes||{})},strengths:current.strengths,improvementAreas:current.improvementAreas,actionPlan:current.actionPlan,recommendations:current.recommendations,overallRating:current.overallRating,originalSubmittedAt:text(current.submittedAt),originalSubmittedBy:text(current.submittedBy),sourceWorkflowVersion:workflowVersionOf(current),createdAt:now,createdBy:actorUid} as SupervisorCoachingPreRevisionSnapshot});
  const updates={status:"DRAFT" as const,workflowPhase:"REVISION_DRAFT" as const,workflowVersion:version,revisionCount:1 as const,supervisorDisagreementResolution:"REVISE" as const,supervisorDisagreementResolvedAt:now,supervisorDisagreementResolvedBy:actorUid,revisionOpenedAt:now,revisionOpenedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("REPRESENTATIVE_REVIEWED","DRAFT","OPEN_REVISION",actorUid,scope.role as Role,now,"SUPERVISOR_DISAGREEMENT_REVIEW","REVISION_DRAFT",undefined,1)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"REPRESENTATIVE_REVIEWED","DRAFT","Coaching Appraisal Revision Opened",now,"SUPERVISOR_DISAGREEMENT_REVIEW","REVISION_DRAFT",version,undefined,1));return{success:true,appraisal:updated!};
}
export async function saveSupervisorAppraisalRevision(actorUid:string,input:AppraisalRevisionSave,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"DRAFT","REVISION_DRAFT",revisionGuard),visit=await repo.getVisit(appraisal.supervisorVisitId);if(!visit||!["IN_PROGRESS","COMPLETED"].includes(visit.status))throw new SupervisorVisitError("APPRAISAL_EDIT_REQUIRES_ACTIVE_OR_COMPLETED_VISIT",409);
  const now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),updates={scores:input.scores,comments:input.comments,sectionNotes:input.sectionNotes,strengths:input.strengths,improvementAreas:input.improvementAreas,actionPlan:input.actionPlan,recommendations:input.recommendations,overallRating:input.overallRating,workflowVersion:version,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("DRAFT","DRAFT","SAVE_REVISION",actorUid,scope.role as Role,now,"REVISION_DRAFT","REVISION_DRAFT",undefined,1)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"DRAFT","DRAFT","Coaching Appraisal Revision Saved",now,"REVISION_DRAFT","REVISION_DRAFT",version,undefined,1));return{success:true,appraisal:updated!};
}
export async function submitSupervisorAppraisalRevision(actorUid:string,input:AppraisalSubmit,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"DRAFT","REVISION_DRAFT",revisionGuard),visit=await repo.getVisit(appraisal.supervisorVisitId);if(!visit||!["IN_PROGRESS","COMPLETED"].includes(visit.status))throw new SupervisorVisitError("APPRAISAL_SUBMIT_VISIT_STATE_DENIED",409);if(!appraisalComplete(appraisal))throw new SupervisorVisitError("APPRAISAL_INCOMPLETE",409);
  const now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),updates={status:"PENDING_CONFIRMATION" as const,workflowPhase:"FINAL_REPRESENTATIVE_REVIEW" as const,workflowVersion:version,revisionSubmittedAt:now,revisionSubmittedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("DRAFT","PENDING_CONFIRMATION","SUBMIT_REVISION",actorUid,scope.role as Role,now,"REVISION_DRAFT","FINAL_REPRESENTATIVE_REVIEW",undefined,1)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"DRAFT","PENDING_CONFIRMATION","Coaching Appraisal Revision Submitted",now,"REVISION_DRAFT","FINAL_REPRESENTATIVE_REVIEW",version,undefined,1));return{success:true,appraisal:updated!};
}
export async function finalReviewSupervisorAppraisal(actorUid:string,input:AppraisalFinalRepresentativeReview,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  if(input.reviewDecision!=="ACKNOWLEDGE_REVISED_APPRAISAL")throw new SupervisorVisitError("INVALID_FINAL_REPRESENTATIVE_REVIEW_DECISION",400);
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await coachingActor(actorUid,deps.scopeRepository);if(![Role.MEDICAL_REP,Role.SALES_REP].includes(scope.role as Role))throw new SupervisorVisitError("REPRESENTATIVE_REVIEW_ROLE_DENIED");const appraisal=await repo.getAppraisal(input.appraisalId);if(!appraisal||appraisal.representativeId!==actorUid||appraisal.representativeRole!==scope.role)throw new SupervisorVisitError("APPRAISAL_NOT_FOUND_OR_DENIED",404);const guard=(current:SupervisorCoachingAppraisal)=>revisionGuard(current)||(!current.finalRepresentativeReviewDecision?null:"APPRAISAL_REVIEW_ALREADY_RECORDED"),expectation=mutationExpectation(appraisal,input,actorUid,"REPRESENTATIVE",scope,"PENDING_CONFIRMATION","FINAL_REPRESENTATIVE_REVIEW",guard),now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),updates={status:"REPRESENTATIVE_REVIEWED" as const,workflowPhase:"SUPERVISOR_FINAL_REVIEW" as const,workflowVersion:version,finalRepresentativeReviewDecision:input.reviewDecision,finalRepresentativeComment:input.representativeComment,finalRepresentativeReviewedAt:now,finalRepresentativeReviewedBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED","FINAL_REPRESENTATIVE_REVIEW",actorUid,scope.role as Role,now,"FINAL_REPRESENTATIVE_REVIEW","SUPERVISOR_FINAL_REVIEW",input.reviewDecision,1)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"PENDING_CONFIRMATION","REPRESENTATIVE_REVIEWED","Coaching Appraisal Final Representative Review",now,"FINAL_REPRESENTATIVE_REVIEW","SUPERVISOR_FINAL_REVIEW",version,input.reviewDecision,1));return{success:true,appraisal:updated!};
}
export async function signOffSupervisorAppraisal(actorUid:string,input:AppraisalSignOff,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository;now?:()=>string;auditId?:()=>string}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),{scope,appraisal}=await supervisorAppraisalContext(actorUid,input.appraisalId,repo,deps.scopeRepository),guard=(current:SupervisorCoachingAppraisal)=>{if(current.representativeReviewDecision==="ACKNOWLEDGED"&&revisionCountOf(current)===0)return null;if(current.representativeReviewDecision!=="DISAGREE_REQUEST_REVIEW")return"APPRAISAL_SIGN_OFF_NOT_READY";if(current.supervisorDisagreementResolution==="KEEP_UNCHANGED"&&Boolean(text(current.supervisorDisagreementRationale))&&revisionCountOf(current)===0)return null;if(current.supervisorDisagreementResolution==="REVISE"&&revisionGuard(current)===null&&Boolean(current.finalRepresentativeReviewDecision))return null;return"APPRAISAL_SIGN_OFF_NOT_READY";},expectation=mutationExpectation(appraisal,input,actorUid,"SUPERVISOR",scope,"REPRESENTATIVE_REVIEWED","SUPERVISOR_FINAL_REVIEW",guard),now=(deps.now||(()=>new Date().toISOString()))(),version=nextVersion(appraisal),updates={status:"SIGNED_OFF" as const,workflowPhase:"FINALIZED" as const,workflowVersion:version,signedOffAt:now,signedOffBy:actorUid,updatedAt:now,updatedBy:actorUid,workflowHistory:[...(appraisal.workflowHistory||[]),workflowEvent("REPRESENTATIVE_REVIEWED","SIGNED_OFF","SIGN_OFF",actorUid,scope.role as Role,now,"SUPERVISOR_FINAL_REVIEW","FINALIZED",undefined,revisionCountOf(appraisal)||0)]},auditId=(deps.auditId||(()=>`AUD-COACH-${randomUUID()}`))(),updated=await repo.updateAppraisal(appraisal.id,expectation,updates,workflowAudit(auditId,actorUid,scope.role as Role,appraisal.id,appraisal.supervisorVisitId,"REPRESENTATIVE_REVIEWED","SIGNED_OFF","Coaching Appraisal Signed Off",now,"SUPERVISOR_FINAL_REVIEW","FINALIZED",version,undefined,revisionCountOf(appraisal)||0));return{success:true,appraisal:updated!};
}
export async function readSupervisorAppraisals(actorUid:string,deps:{repository?:SupervisorVisitRepository;scopeRepository?:OperationalScopeRepository}={}){
  const repo=deps.repository||createFirestoreSupervisorVisitRepository(),scope=await coachingActor(actorUid,deps.scopeRepository),supervisor=[Role.MEDICAL_SUPERVISOR,Role.SALES_SUPERVISOR].includes(scope.role as Role);
  const rows=supervisor?await repo.listSupervisorAppraisals(actorUid):await repo.listRepresentativeAppraisals(actorUid),appraisals=rows.filter(a=>supervisor?a.supervisorId===actorUid&&scope.areaIds.includes(a.areaId):a.representativeId===actorUid&&a.representativeRole===scope.role),visits=await Promise.all(appraisals.map(a=>repo.getVisit(a.supervisorVisitId)));
  return{authorized:true,appraisals,visits:Object.fromEntries(visits.filter(Boolean).map(v=>[v!.id,v])),supervisors:await resolveSupervisorIdentityPresentations(appraisals,repo)};
}
export async function readSupervisorVisitOptions(actorUid: string, deps: { scopeRepository?: OperationalScopeRepository } = {}) { const scopeRepository=deps.scopeRepository||createFirestoreOperationalScopeRepository(), scope=await context(actorUid,scopeRepository), catalog=await scopeRepository.getGeographyCatalog(), allowed=new Set(scope.areaIds),countries=new Map(catalog.countries.map(x=>[x.id,x.name||x.id])),districts=new Map(catalog.districts.map(x=>[x.id,x.name||x.id])),cities=new Map(catalog.cities.map(x=>[x.id,x.name||x.id])); return { authorized:true, areas:catalog.areas.filter(a=>allowed.has(a.id)&&a.active!==false&&a.status!=="Inactive").map(a=>({id:a.id,name:a.name||a.id,countryId:text(a.countryId),countryName:countries.get(text(a.countryId))||text(a.countryId),districtId:text(a.districtId),districtName:districts.get(text(a.districtId))||text(a.districtId),cityId:text(a.cityId),cityName:cities.get(text(a.cityId))||text(a.cityId)})) }; }
