import React, { useMemo, useState } from "react";
import { ArrowLeft, Calendar, MapPin, Stethoscope, User } from "lucide-react";
import type { Physician, PhysicianVisit } from "../../types";

interface PhysicianProfileProps { lang: "en" | "ar"; onNavigate?: (target: string) => void; physicians: Physician[]; physicianVisits: PhysicianVisit[] }

export default function PhysicianProfile({ lang, onNavigate, physicians, physicianVisits }: PhysicianProfileProps) {
  const isRtl = lang === "ar"; const [selectedId, setSelectedId] = useState(physicians[0]?.id || "");
  const current = physicians.find(item => item.id === selectedId) || physicians[0] || null;
  const visits = useMemo(() => current ? physicianVisits.filter(visit => visit.physicianId === current.id).sort((a, b) => String(b.visitDate || b.createdAt).localeCompare(String(a.visitDate || a.createdAt))) : [], [current?.id, physicianVisits]);
  return <div className="p-6 max-w-5xl mx-auto space-y-6" dir={isRtl ? "rtl" : "ltr"}>
    <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4"><div className="flex items-center gap-3"><button onClick={() => onNavigate?.("field-physician-list")} className="p-2 rounded-xl border"><ArrowLeft size={16}/></button><div><h2 className="text-lg font-bold">{isRtl ? "الملف التعريفي للأطباء" : "Physician Academic Profile & Ledger"}</h2><p className="text-xxs text-slate-400">{isRtl ? "بيانات الطبيب وسجل الزيارات الفعلي" : "Canonical physician data and scoped visit history."}</p></div></div><select value={current?.id || ""} onChange={event => setSelectedId(event.target.value)} className="text-xs p-2 rounded-lg border bg-transparent"><option value="" disabled>{isRtl ? "اختر طبيباً" : "Select physician"}</option>{physicians.map(item => <option key={item.id} value={item.id}>{isRtl ? item.nameAr || item.name : item.name}</option>)}</select></div>
    {!current ? <div className="rounded-2xl border p-10 text-center text-sm text-slate-500">{isRtl ? "لا يوجد أطباء ضمن النطاق المصرح" : "No physicians are available in the authorized scope."}</div> : <><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="rounded-2xl border p-5 text-center"><User className="mx-auto text-slate-400" size={32}/><h3 className="mt-3 font-bold">{isRtl ? current.nameAr || current.name : current.name}</h3><p className="text-xs text-indigo-600 flex justify-center gap-1"><Stethoscope size={12}/>{current.specialty}</p><span className="mt-3 inline-block rounded bg-indigo-50 px-2 py-1 text-xs">Class {current.classification}</span></div><div className="lg:col-span-2 rounded-2xl border p-5 space-y-3 text-xs"><p className="flex gap-2"><MapPin size={14}/>{[current.countryName || current.country, current.districtName || current.district, current.cityName || current.city, current.areaName || current.area].filter(Boolean).join(" / ") || "Geography not configured"}</p><p>{current.address}</p><p>{isRtl ? "مجموعة الترويج الرئيسية" : "Primary Promotion Group"}: <strong>{current.primaryPromotionGroupName || current.primaryPromotionGroupId || (isRtl ? "غير مكوّن" : "Configuration required")}</strong></p><p>{isRtl ? "إجمالي الزيارات" : "Total visits"}: <strong>{visits.length}</strong></p></div></div><div className="rounded-2xl border p-5"><h3 className="font-bold text-sm mb-3 flex gap-2"><Calendar size={15}/>{isRtl ? "سجل المناقشات والزيارات" : "Visit & discussion history"}</h3>{visits.length ? <div className="divide-y">{visits.map(visit => <div key={visit.id} className="py-3 text-xs"><strong>{visit.displayNumber || visit.id}</strong><span className="mx-2 text-slate-400">{visit.visitDate || visit.date}</span><p className="text-slate-500 mt-1">{visit.generalNotes || visit.overallVisitNotes || (isRtl ? "لا توجد ملاحظات" : "No discussion notes recorded")}</p></div>)}</div> : <p className="text-xs text-slate-500">{isRtl ? "لا توجد زيارات مسجلة" : "No persisted visits for this physician."}</p>}</div></>}
  </div>;
}
