import fs from "node:fs";
import { describe, expect, it } from "vitest";
import { Role } from "./types";
import { defaultNavigationVisible } from "./lib/accessGovernance";
import { autoCheckoutOpenSession, calculateAttendanceSummary, checkInAttendance, manualCheckout } from "./lib/attendanceEngine";
import { createConfigurationAuditEvent } from "./lib/configurationAudit";
import { aggregateSingleCurrency, formatMarketCurrency, JORDAN_MARKET_DEFAULT, LIBYA_MARKET_DEFAULT, resolveBusinessCalendarDay } from "./lib/marketSettings";
import { auditProductAssignments } from "./lib/productAssignmentAudit";
import { applyOrderTransitionWithTemplate, ENTERPRISE_WORKFLOW_TEMPLATE } from "./features/orders/orderWorkflowTemplate";

describe("WP77 integrated governance regression", () => {
  it("supports two explicit markets, currency formatting and mixed-currency refusal", () => { expect(formatMarketCurrency(1, LIBYA_MARKET_DEFAULT)).toContain("LYD"); expect(formatMarketCurrency(1, JORDAN_MARKET_DEFAULT)).toContain("JOD"); expect(() => aggregateSingleCurrency([{ amount: 1, currencyCode: "LYD" }, { amount: 1, currencyCode: "JOD" }])).toThrow(); });
  it("resolves weekend, holiday and exceptional working precedence", () => { expect(resolveBusinessCalendarDay("2026-08-14", LIBYA_MARKET_DEFAULT, []).reason).toBe("WEEKEND"); const exceptional: any = { id: "E", marketId: LIBYA_MARKET_DEFAULT.marketId, countryId: LIBYA_MARKET_DEFAULT.countryId, date: "2026-08-14", nameEn: "Work", nameAr: "عمل", type: "EXCEPTIONAL_WORKING", active: true, createdBy: "A", createdAt: "x", updatedBy: "A", updatedAt: "x" }; expect(resolveBusinessCalendarDay("2026-08-14", LIBYA_MARKET_DEFAULT, [exceptional]).scheduledWorkingDay).toBe(true); });
  it("keeps manual and forgotten checkout semantics distinct", () => { const open: any = checkInAttendance({ id: "S", userId: "U", marketId: LIBYA_MARKET_DEFAULT.marketId, countryId: LIBYA_MARKET_DEFAULT.countryId, date: "2026-08-16", timezone: LIBYA_MARKET_DEFAULT.timezone, scheduledStart: "2026-08-16T05:30:00Z", scheduledEnd: "2026-08-16T13:30:00Z", actualCheckIn: "2026-08-16T05:30:00Z", createdBy: "U", createdAt: "2026-08-16T05:30:00Z", updatedBy: "U", updatedAt: "2026-08-16T05:30:00Z" }, 15); expect(autoCheckoutOpenSession(manualCheckout(open, "2026-08-16T13:05:00Z"), "2026-08-16T18:00:00Z", 480).checkoutMode).toBe("MANUAL"); expect(autoCheckoutOpenSession(open, "2026-08-16T18:00:00Z", 480).actualCheckOut).toBe("2026-08-16T13:30:00.000Z"); });
  it("pins attendance denominator", () => expect(calculateAttendanceSummary({ userId: "U", fromDate: "2026-08-16", toDate: "2026-08-16", market: LIBYA_MARKET_DEFAULT, exceptions: [], sessions: [], leaves: [{ id: "L", userId: "U", marketId: LIBYA_MARKET_DEFAULT.marketId, startDate: "2026-08-16", endDate: "2026-08-16", type: "ANNUAL", status: "APPROVED" }] }).expectedAttendanceDays).toBe(0));
  it("pins required navigation allow/deny boundaries", () => { expect(defaultNavigationVisible(Role.PRODUCT_MANAGER, "FIELD_OPERATIONS")).toBe(true); expect(defaultNavigationVisible(Role.MEDICAL_SUPERVISOR, "PHARMACIES")).toBe(true); expect(defaultNavigationVisible(Role.SALES_MANAGER, "FIELD_OPERATIONS")).toBe(false); expect(defaultNavigationVisible(Role.ORDER_OPS_OFFICER, "PHARMACIES")).toBe(false); });
  it("preserves separate order audit transitions", () => { const result = applyOrderTransitionWithTemplate({ order: { id: "O", displayNumber: "O", status: "PENDING_FINANCE_REVIEW", createdByUid: "R", history: [] }, action: "FINANCE_APPROVE", actor: { uid: "F", role: Role.FINANCE }, template: ENTERPRISE_WORKFLOW_TEMPLATE, source: "BACKEND" }); expect(result.historyEntry).toMatchObject({ action: "FINANCE_APPROVE", actorUid: "F" }); });
  it("uses real assignment inputs and typed configuration audit", () => { expect(auditProductAssignments({ users: [], assignments: [], products: [], promotionGroups: [], territoryAssignments: [] }).generatedFromCanonicalData).toBe(true); expect(createConfigurationAuditEvent({ domain: "MARKET", entityId: "M", action: "UPDATE", actorUid: "A", actorRole: "Admin", occurredAt: "2026-08-16T00:00:00Z", before: { currency: "LYD" }, after: { currency: "JOD" } }).changedFields).toEqual(["currency"]); });
  it("removes Team Activity and Leave demo records", () => { const team = fs.readFileSync(new URL("./components/supervision/TeamActivity.tsx", import.meta.url), "utf8"); const leave = fs.readFileSync(new URL("./components/supervision/LeaveApprovals.tsx", import.meta.url), "utf8"); expect(team).not.toContain("Omar Al-Mokhtar"); expect(team).not.toContain("Math.random()"); expect(leave).not.toContain("LV-2026-012"); });
  it("removes static Administration market IDs and localStorage workflow authority", () => { const admin = fs.readFileSync(new URL("./components/Administration.tsx", import.meta.url), "utf8"); expect(admin).not.toContain("C-LIB-8842"); expect(admin).not.toContain("C-JOR-9875"); expect(admin).not.toContain("pharma_crm_workflow_rules"); expect(admin).toContain('"orderWorkflowTemplates"'); expect(admin).toContain('"configurationAudit"'); });
  it("wires canonical settings, scoped team activity and recovery endpoints", () => { const server = fs.readFileSync(new URL("../server.ts", import.meta.url), "utf8"); for (const endpoint of ["/api/team-activity/scoped-query", "/api/leave-requests/mutate", "/api/attendance/process-open-sessions", "/api/analytics/products/scoped-query"]) expect(server).toContain(`app.post(\"${endpoint}\", requireFirebaseAuth`); const admin = fs.readFileSync(new URL("./components/Administration.tsx", import.meta.url), "utf8"); expect(admin).toContain('"businessCalendarExceptions"'); expect(admin).toContain("validateMarketSettings"); });
  it("removes broad analytics scans and demo product analytics", () => { const reports = fs.readFileSync(new URL("./components/analytics/ReportsHubPage.tsx", import.meta.url), "utf8"); const products = fs.readFileSync(new URL("./components/analytics/ProductDashboardPage.tsx", import.meta.url), "utf8"); expect(reports).not.toContain('getDocs(collection(db, "orders"))'); expect(products).not.toContain('getDocs(collection(db, "orders"))'); expect(products).not.toContain("pharma_crm_orders"); for (const demo of ["CardioMax 10mg", "KidVits Chewable", "LYD 165K Est."]) expect(products).not.toContain(demo); });
  it("removes browser-local order workflow authority", () => { const orders = fs.readFileSync(new URL("./components/sales/SalesOrders.tsx", import.meta.url), "utf8"); expect(orders).not.toContain("pharma_crm_workflow_rules"); expect(orders).toContain("applyOrderTransitionWithTemplate"); expect(orders).toContain('"orderWorkflowTemplates"'); });
  it("preserves WP76J roles and server query", () => { const visits = fs.readFileSync(new URL("../server/physicianVisitReadService.ts", import.meta.url), "utf8"); for (const role of ["Super Admin", "Admin", "Medical Supervisor", "Medical Representative"]) expect(visits).toContain(`\"${role}\"`); expect(visits).toContain('.where("repId", "in", subjects)'); });
});
